### ISSUE TITLE
ARM64 docker-compose

### ISSUE THREAD

**Issue by gridworkz** [getlago/lago#100]
Is there an ARM64 version of docker-compose available by any chance?

**Comment by jdenquin** [comment]
We are working on it and it should be available very soon!

**Comment by gridworkz** [comment]
Cool, thanks for the update.

**Comment by TarekMahran** [comment]
+1

**Comment by jdenquin** [comment]
Hello guys,

Here is the `docker-compose` file for ARM64 support!
https://github.com/getlago/lago/blob/main/docker-compose.arm64.yml

I close this issue, do not hesitates if you have some questions around it!

**Comment by gridworkz** [comment]
That's wicked! Cheers, Dave
