### ISSUE TITLE
Dump Lago data into data warehouses

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#103]
## Problem description
It's currently not possible to dump Lago's data into warehouses to query it for revenue analysis, or data activation

**Comment by joaolcorreia** [comment]
This shouldn't be needed. If one wants the billing data all it takes is connecting the Lago PostgreSQL to Snowflake using Fivetran or Airbyte and perform some SQL magic.

**Comment by sarkissianraffi** [comment]
Hi @joaolcorreia, actually you are right for self-hosted users, but that's not the case for cloud hosted users. However, an existing alternative has been created with Airbyte => https://docs.airbyte.com/integrations/sources/getlago/
