### ISSUE TITLE
Send invoices and retries by email directly from Lago

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#104]
## Problem description
Currently, you need to connect your own emailing tool to send invoices or retries when an invoice is not paid. We want to ease your life by sending invoices directly from Lago

**Comment by michaelponrajah** [comment]
## We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Send invoices and retries by email - Canny](https://getlago.canny.io/feature-requests/p/send-invoices-by-email)
