### ISSUE TITLE
Can't turn on Signup

### ISSUE THREAD

**Issue by gridworkz** [getlago/lago#107]
I'm running locally and I wanted to turn on the SignUp / Register feature. I set: `LAGO_DISABLE_SIGNUP=false` in the `.env` file from the main `lago` directory. Whatever I try, the SIgnup button is always greyed out. What could I be missing? Cheers, Dave

**Comment by jdenquin** [comment]
Hello @gridworkz 

The SignUp feature is activated by default, let's check if your configuraton is ok!
Did you changed any env var value? the `LAGO_DISABLE_SIGNUP` is empty by default, you can remove it from the `.env` file you created.

**Comment by gridworkz** [comment]
sorry, I'm a bonehead. I just wasn't entering in enough password characters to satisfy the security criteria - once I met all the password criteria the Signin lit up!

**Comment by michaelponrajah** [comment]
Hey @gridworkz, interesting to see this behaviour, I'm logging it and see how we can improve it if it occurs again! It the meantime, I'll close this issue, feel free to reach us if you need anything :)
