### ISSUE TITLE
[FEAT]: deployment with nginx alongside other domains

### ISSUE THREAD

**Issue by jakubmirejovsky** [getlago/lago#110]
Hi, can we get a guide how to install Lago for use under nginx?
We have a Ubuntu server with multiple apps, each running on its own port. We use nginx for proxying domains to localhosts.
When I try to docker compose up Lago, I'm getting error with port 443 being in use.

I'm wondering if there is any way to install Lago with no public ports (no 80 or 443, only 3000)?

Thanks! :)

**Comment by jdenquin** [comment]
Hello @jakubmirejovsky 

We already use NGINX for the Front end docker image.
You can change the port forwarding into the `docker-compose.yml` file like this : 

```yaml
ports:
    - 3001:80
```

So the front end will be available on the `3001` port and no more `80` and `443`. Tell me if it helps and if you need more help around this!

**Comment by jakubmirejovsky** [comment]
Thank you!
After some additional digging, this is what I've done to get it up and running:

I set up two separate virtual hosts on my server's nginx config. Here is a sample:
```upstream lago {
server 127.0.0.1:3001;
}

server {
# Listen HTTP
server_name my-frontend-public-domain.tld;

location / {
proxy_pass http://lago;
proxy_http_version 1.1;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-NginX-Proxy true;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_pass_request_headers on;
}

    error_log /var/log/nginx/lago.error.log;
    access_log /var/log/nginx/lago.access.log;

    listen 80;
}
```

I did the same for Lago's backend API. (= I have two public-facing domains, eg. mylago.com and api.mylago.com).

I then edited the .env of Lago, I added:
`LAGO_API_URL=my-backend-public-domain.tld`

This way the docker was able to start up, but I got some CORS issues with graphql, meaning the backend API proxy was not set correctly. I added this to my nginx config:

```
location / {
    add_header 'Access-Control-Allow-Origin' 'my-frontend-public-domain.tld';
    add_header 'Access-Control-Allow-Headers' '*';
}
```

And it worked! Then I just used certbot to generate my public-facing certificates and to enable https.
Leaving this here for anyone who will google for answers.

imho, this should be a part of the manual - for people setting Lago up alongside their running apps.

Feel free to close this issue or correct me if I'm not seeing an easier way.

**Comment by jdenquin** [comment]
Awesome!

I've never digged into this kind of configuration right now but I'll add it somewhere in our documentation.

For the CORS issue you have to update the `LAGO_FRONT_URL` at the `api` level to your current front domain!
