### ISSUE TITLE
[FEAT]: valid payment method field with date of last check

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago#114]
For business purposes and help with forecasting of continuing renewals, it would be useful to be able to set periodic checks of whether a customer's payment method is still valid and display this status along with the last date/time of check.

**Comment by michaelponrajah** [comment]
Hey @c-nv-s , 
Thanks for the issue and request.
I guess it’s not on our scope for now. Even if this wouldn’t require to be PCI DSS (to store payment method info), this information is not useful for the billing engine for now. 

I guess it’s better to ask your PSPs to handle this info and give visibility on payment method status

**Comment by c-nv-s** [comment]
Ok, but just to clarify I am not requesting to store any payment details but just a status true/false that the payment method for the subscription is still valid and the date it was last checked. Anyway if that is not achievable, or if that breaks compliance then I understand.

**Comment by c-nv-s** [comment]
I just wanted to add this here as I think it is relevant to this ticket.
As per step number 4. here: https://doc.getlago.com/docs/guide/payments/stripe-integration#new-billing-and-payment-system
If you try to add a customer to a subscription before they have added a payment method to stripe it will fail.
So it would actually be useful if lago had some way to advise if the customer has already added a payment method.
knowing this, you can then either present an 'add payment method' button to the customer's dashboard or go straight ahead and load the dashboard with their invoice history.
Just food for thought.

**Comment by michaelponrajah** [comment]
Thanks for the details, we're actually discussing internally on it, we'll get to you asap on it! 

So far, we don't want to store payment method information but storing if TRUE/FALSE payment method exists and users switches the status could be one way, they should other way also, so we'll dig on it and see when we can prioritise it 🙌
