### ISSUE TITLE
[FEAT]: Integration with Recur360 payments platform

### ISSUE THREAD

**Issue by jpattWPC** [getlago/lago#116]
**Is your feature request related to a problem? Please describe.**
No problem, just a requested feature

**Describe the solution you'd like**
Recur360 is a recurring payments platform that neatly integrates with Quickbooks. Recur360 takes care of integrating with various payment processors and Quickbooks, which means that reconciling Lago with Quickbooks will no longer be a tedious, manual task.

The ideal integration would allow any payments made to an invoice through Recur360 to be automatically applied in Lago, and any manual payments entered into Lago to be applied to the invoice in Recur360. Any new invoices that are created in Lago should be automatically pushed to Recur360

**Describe alternatives you've considered**
A full integration with Quickbooks invoices would also be acceptable, provided that the past due invoice reminder functionalities of Recur360 are also available in Lago.

**Additional context**
Information about the Recur360 API is available here: https://www.recur360.com/features/api-and-integrations

**Comment by mathieu-lago** [comment]
Thanks for your contribution, @jpattWPC! I guess our preferred option would be a native integration with QuickBooks as it's been requested by other users as well, but we will take a look at Recur360.

Is Recur360 + Paya your main payment gateway or do you also use other PSPs?

**Comment by jpattWPC** [comment]
We use Recur360 + Authorize.net to process all of our CC and eCheck transactions.

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/integration-with-recur360
