### ISSUE TITLE
[FEAT]: Calculate single usage item for a group of usage items sent in an event

### ISSUE THREAD

**Issue by jpattWPC** [getlago/lago#117]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request

**Describe the solution you'd like**
The ability to receive events with a group of usage items, and have basic calculations performed on them to add to the total. For example:

- The following group of usage items (in seconds) would be received, but only a single usage item needs to be billed in Lago (such as TotalMinutes):
  - InboundTime
  - OutboundTime
  - WorkTime
  - ConferenceTime
  - ParkTime
  - HoldTime
- As an example, the following ‘excel’ calculation would be performed to determine the metric amount:
  - =(CEILING(InboundTime + OutboundTime + WorkTime + ConferenceTime + WorkTime + (HoldTime - ParkTime)), 30)/60)
  - This calculation performs the following:
    - Subtracts ParkTime from HoldTime
    - Adds the previous value to all other values
    - Rounds the value up to the nearest 30 seconds
    - Divides by 60 to get the number of minutes

The general idea is to be able to apply a calculation 'formula' for a particular group of metrics received as an event, and apply the result of that calculation to a single metric.A clear and concise description of any alternative solutions or features you've considered.
 
**Describe alternatives you've considered**
Have the platform that is sending these events perform these calculations prior to sending them to Lago. The main issue with this is it may be useful to have different calculation formulas per account which may be difficult to do in an external system.

**Additional context**

**Comment by mathieu-lago** [comment]
That's an interesting feature, @jpattWPC. Would you be available next week to discuss it with our team? I sent you an email earlier, please feel free to get back to me here on GitHub or by email.

**Comment by jpattWPC** [comment]
I responded to your email, looking forward to chatting with you next week!
