### ISSUE TITLE
[FEAT]: add usage based coupons

### ISSUE THREAD

**Issue by derekperkins** [getlago/lago#118]
**Is your feature request related to a problem? Please describe.**
We incentivize customers to perform actions during onboarding, write reviews, share us on social media, etc., and in exchange, we offer free usage. Sometimes this is in the form of a recurring credit, e.g. Write a review on G2 and get 1,000 monthly units (no rollover) for 12 months. Other times it is just a bulk credit: 1,000 units that expire in 12 months. 

**Describe the solution you'd like**
Create a coupon for a specific usage type and apply those to usage before calculating overage.

**Describe alternatives you've considered**
Today in Chargebee, we have to create a matrix of $ coupons that map to the unit price of each plan.

**Comment by derekperkins** [comment]
cc @MordFustang21

**Comment by mathieu-lago** [comment]
There are different ways of approaching this (the 'coupons' feature is one of them). For the time being, I would suggest creating customer wallets and granting free credits when the customer completes a task, but this is also something I'd like to discuss with you to ensure this is the optimal solution.

Prepaid credits (guide): https://doc.getlago.com/docs/guide/prepaid_credits
Wallet creation via API: https://doc.getlago.com/docs/api/wallets/create-wallet
Wallet top-up via API: https://doc.getlago.com/docs/api/wallets/top-up

**Comment by derekperkins** [comment]
The main issue with that is that I don't want to discount their actual plan, I just want to grant extra free usage. I'm not set on it being a coupon, but I do want them to show up as line items on invoices so that customers can see that they are being applied.

**Comment by sarkissianraffi** [comment]
@derekperkins The prepaid credits granted offer extra free usage that is not being charged at the end of the period. It will be displayed on invoices. This feature has been made to grant extra free usage for actions being performed that are not directly related to a coupon.

If this does not fit, it would be great to jump on a call to understand what you have in mind.

**Comment by mathieu-lago** [comment]
Users can grant free credits using the wallet feature or create coupons limited to specific billable metrics.

https://doc.getlago.com/docs/guide/prepaid_credits
https://doc.getlago.com/changelog/coupons-metrics
