### ISSUE TITLE
[FEAT]: Avalara integration

### ISSUE THREAD

**Issue by derekperkins** [getlago/lago#119]
**Is your feature request related to a problem? Please describe.**
Tax calculation is hard, and we rely on Avalara.

**Describe the solution you'd like**
Have tax rates calculated automatically via Avalara

**Describe alternatives you've considered**
We would have to manually listen for Lago webhooks and apply tax rates ourselves

**Additional context**
Avalara is probably the most common integration supported by other platforms, other options are Stripe Tax and TaxJar, but we have no interest in those

**Comment by derekperkins** [comment]
cc @MordFustang21

**Comment by mathieu-lago** [comment]
We are considering several options at the moment, including new tax features (e.g. set a tax rate at charge level) and native integrations as well. It would be interesting to discuss this together during our call next week. Having a better understanding of your needs could help us make a decision on this topic.

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/avalara-avatax-integration

Related feature (in progress): https://getlago.canny.io/feature-requests/p/create-several-tax-rates
