### ISSUE TITLE
[FEAT]: Xero integration

### ISSUE THREAD

**Issue by derekperkins** [getlago/lago#120]
**Is your feature request related to a problem? Please describe.**
Billing that doesn't sync into an accounting system isn't very useful

**Describe the solution you'd like**
Sync customers and invoices into Xero

**Describe alternatives you've considered**
Manually pushing data in via webhooks

**Comment by derekperkins** [comment]
cc @mordfustang21

**Comment by mathieu-lago** [comment]
Thanks for your contribution, @derekperkins! As you mentioned, for the moment you can retrieve invoices through our webhook and then push this information to your accounting software. Native accounting integrations (e.g. QuickBooks, Xero) are also on our roadmap, so we'll be happy to scope this feature with your team.

**Comment by decnorton** [comment]
We'd also be interested in an integration with Xero and happy to work with you to scope it out

**Comment by mathieu-lago** [comment]
Hi @decnorton - thanks for your message!
It would be useful to review your billing needs and requirements for this integration. Would you be available for a quick call this week?

**Comment by decnorton** [comment]
@mathieu-lago Of course, feel free to reach out on dn @ carelinelive.com

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/integration-with-xero
