### ISSUE TITLE
[FEAT]: AWS Marketplace integration 

### ISSUE THREAD

**Issue by maciejstromich** [getlago/lago#126]
**Is your feature request related to a problem? Please describe.**
For customers that are AWS Marketplace customers it would be beneficial to send hourly reports to AWS to correctly bill them. Maybe integrate in a way that Lago gets the AWS Marketplace subscriptions automatically into it's database

**Comment by sarkissianraffi** [comment]
Hi @maciejstromich, that’s a good feature request, indeed. We’ve already planed to work on this integration. 

Could be great to have a quick call with you when we start scoping the feature. 
thanks!

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/aws-marketplace-integration
