### ISSUE TITLE
[BUG]: How is https supposed to work ?

### ISSUE THREAD

**Issue by maximelebastard** [getlago/lago#129]
**Describe the bug**
I followed [the documentation](https://doc.getlago.com/docs/guide/self-hosting/docker#ssl-support) about creating and using a self-signed certificate.

Anytime I used https, I had a 404 error and realized nginx was using the default directory `/etc/nginx/html/` as a root and not `/usr/share/nginx/html` as expected.

On the `front` docker image, the nginx configuration makes the https server use a wrong root. But it also redirecs all the http traffic to https.

To make the server work, I had to update the file `/etc/nginx/conf.d/default.conf` from this:

```
server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
    return 301 https://$host$request_uri;
  }

}

server {
  listen 443 ssl;

  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
  ssl_dhparam /etc/ssl/certs/dhparam.pem;
}
```

To this:

```
server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
    return 301 https://$host$request_uri;
  }

}

server {
  listen 443 ssl;

  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
  ssl_dhparam /etc/ssl/certs/dhparam.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}
```

I don't understand how the HTTPS option is supposed to work with that NGINX configuration.

**To Reproduce**

1. Clone the repo
2. Run `./extras/init-selfsigned.sh`
3. Run `docker-compose up -d`
4. Try to access http://localhost, you'll get redirected to https://localhost
5. When accessing https://localhost, you'll get a 404 error

**Expected behavior**

1. Clone the repo
2. Run `./extras/init-selfsigned.sh`
3. Run `docker-compose up -d`
4. Try to access http://localhost, you'll get redirected to https://localhost
5. When accessing https://localhost, you'll get Lago

More technically: I would expect the https nginx server to use the Lago app as the root directory

**Support**
Version: v0.14.0-alpha
Hoster: AWS EC2

**Comment by mathieu-lago** [comment]
Hi @maximelebastard - thanks for reaching out to us!

Our Engineering team will look into this and get back to you with an update.
