### ISSUE TITLE
[FEAT]: ability to create one-off invoices

### ISSUE THREAD

**Issue by pflynn02** [getlago/lago#133]
**Is your feature request related to a problem? Please describe.**
There is no ability to go to a customer and just generate an invoice once and add line items to it.

**Describe the solution you'd like**
The ability to visit a customer, create an invoice, add line items, quantity, price and set an exact date the invoice is generated. Could be generated immediately or scheduled to run at a set date.

**Describe alternatives you've considered**
This platform is excellent for subscribtion based billing needs but as a consultant who offers subscriptions, I also need the ability to create a one-off invoice for a client when setting up a website or performing random work outside of their subscription. Running this all in 1 system would be excellent, currently I have 2 separate platforms and its sloppy.

**Additional context**
Ping me on Slack if you have more questions or on here.

**Comment by mathieu-lago** [comment]
Thanks for your contribution, @pflynn02! As mentioned on Slack, I've logged this request in our product management platform, so that our team can review it next time they discuss roadmap priorities.

**Comment by mathieu-lago** [comment]
In progress - see here: https://getlago.canny.io/feature-requests/p/ability-to-create-one-off-invoices-with-multiple-items
