### ISSUE TITLE
[FEAT]: AWS Eventbridge or SNS Topic integration

### ISSUE THREAD

**Issue by maciejstromich** [getlago/lago#134]
**Is your feature request related to a problem? Please describe.**
It would be awesome if Lago would be able to integrate with AWS Eventbridge to send events like:
- invoice issued
- payment due
- payment processed
- payment problem

in a push fashion. If Eventbridge is chosen set the event's source field to "lago" or something which easily identifies lago

**Comment by mathieu-lago** [comment]
Hi @maciejstromich - thanks for your suggestion! I'll log this feature request, so the team can review it.

In the meantime, you can use some of our existing [webhooks](https://doc.getlago.com/docs/api/webhooks/messages): `invoice.created` and `invoice.payment_failure`.

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/aws-eventbridge-or-sns-topic-integration
