### ISSUE TITLE
[FEAT]: payment successful webhook

### ISSUE THREAD

**Issue by arjunyel** [getlago/lago#145]
**Is your feature request related to a problem? Please describe.**

This is a request for at least the Stripe integration.

Currently Lago has a payment failure webhook, but to see if an invoice is paid we have to listen to the Stripe webhooks separately.

**Describe the solution you'd like**

A payment successful webhook, since Lago is already listening to update the invoice status.

**Describe alternatives you've considered**

Listening to Stripe webhooks

**Comment by mathieu-lago** [comment]
Thanks for your contribution, @arjunyel! That makes sense for the native payment integrations. In the meantime, you can use [this endpoint](https://doc.getlago.com/docs/api/invoices/get-all-invoices) to retrieve invoices and their payment status.

**Comment by akshatakulkarni25** [comment]
hey @mathieu-lago , is this issue still open for contribution. i am interested in working on it.

**Comment by mathieu-lago** [comment]
Hi @akshatakulkarni25 - thanks for reaching out! Contributions are always appreciated. Please feel free to submit the PR when it's ready, we'll be happy to review it.

**Comment by akshatakulkarni25** [comment]
thank you
