### ISSUE TITLE
Publish Lago Open API

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#147]
## Problem description
How can I use Lago if I don't use one of pre-built Lago Client ?

**Comment by dannysheridan** [comment]
@michaelponrajah I can help! https://www.buildwithfern.com/docs/intro 

Fern is an open-source specification for describing REST APIs. Define your API in Fern to generate boilerplate server code, SDKs, API documentation, an OpenAPI definition, and a Postman Collection.

**Comment by jdenquin** [comment]
Hey @dannysheridan thanks for the insight but we already built our OpenAPI definition some weeks ago!
