### ISSUE TITLE
Option to apply several times or not the same coupon on a customer

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#148]
## Problem description
As a user, it’s not possible to limit the application of a specific coupon on a single customer to one. 

This cumulation prevents automations on coupons, as coupon can be applied one time and customer can't validate several times the same coupons.

**Comment by mathieu-lago** [comment]
See `reusable` coupon attribute: https://doc.getlago.com/docs/api/coupons/create-coupon
