### ISSUE TITLE
Custum attribute for customer

### ISSUE THREAD

**Issue by bert-air** [getlago/lago#152]
For example I would to add some attribute like (SIREN / TVA number etc...)

**Comment by michaelponrajah** [comment]
Hello @bert-air, thanks for your feedback. There's some fields that you can fill on the customer level (e.g. SIREN : Legal number) but totally understand it's limiting. We're adding it as an improvement on customer object. So far it's not planned before end of the year, we'll get back to you when we're starting to work on it!

**Comment by mathieu-lago** [comment]
Customer metadata available: https://doc.getlago.com/changelog/customer-metadata
