### ISSUE TITLE
[FEAT]: Chartmogul Integration

### ISSUE THREAD

**Issue by bert-air** [getlago/lago#153]
**Is your feature request related to a problem? Please describe.**
We need to have a clear view about our subscription 

**Describe the solution you'd like**
A native integration with chartmobul 

**Describe alternatives you've considered**
Use all in one chargebee 

**Additional context**
/

**Comment by michaelponrajah** [comment]
Hey @bert-air , we're adding it in our list of integrations to implement. So far, our goal is to focus on chore billing feature, there will a big focus in 2023, we'll keep you posted on it!

Could you please give more insights behind the sentence `having a clear view about our subscription` what do you wanna see and what are the use cases?

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/create-integration-for-chartmogul-subscription-analytics-platform
