### ISSUE TITLE
[FEAT]: Search bar

### ISSUE THREAD

**Issue by bidyabhushanbibhu** [getlago/lago#156]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem

**Describe the solution you'd like**
A search section in the Billable metrics, coupons and customers sections. This would really be nice to have feature to ease the search. 

**Describe alternatives you've considered**
Postman or the API is one option but will be a good cx experience from the UI perspective because postman and API is not a good customer experience for the non tech user.

**Comment by mathieu-lago** [comment]
Thanks again for reaching out, @bidyabhushanbibhu!

As mentioned on Slack, we are planning to add a search feature to the user interface for billable metrics, plans, coupons, customers, etc. We will let you know when it's ready. 🔜

**Comment by michaelponrajah** [comment]
## `Search bars` are now live in production 🎉

Hey @bidyabhushanbibhu, you probably saw the new releases but wanted to send you a quick message to tell you that the search bars are now available in Lago product!

### Useful links
[Changelog](https://doc.getlago.com/changelog/search-bar)

**Comment by bidyabhushanbibhu** [comment]
Perfect thanks for this team
