### ISSUE TITLE
[FEAT]: billing_period field in subscription object

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago#160]
currently the billing cycle for a subscription is only shown as ``anniversary`` or ``calendar`` as per docs:

billing_time     String     Not null | Billing time of the subscription.  Possible values- anniversary: Subscription will be billed on each week/month/year anniversary, depending on the plan reccurence- calendar:  Subscription at the end of week/month/year. The first subscription  billing will be at pro-rata if it is not created at the beginning of the  week/month/year

it would be useful to have a field e.g. ``billing_period`` which actually shows the value of the resolution/frequency of the billed subscription: i.e. weekly, monthly or yearly

**Comment by sarkissianraffi** [comment]
Hi @c-nv-s,

This information is retrieved at a Plan level (https://doc.getlago.com/docs/api/plans/plan-object). We could bring it to the subscriptions object, but just want to make sure that this interval on the plan's object is not enough for you, and why? (please feel free to comment any use cases you have encountered)

**Comment by c-nv-s** [comment]
Ah ok I will work with it from there... Closing this
