### ISSUE TITLE
[FEAT]: Support for CLF currency

### ISSUE THREAD

**Issue by jerosalazar** [getlago/lago#163]
**Is your feature request related to a problem? Please describe.**
In Chile we usually use two different currencies, CLP (the traditional Chilean Peso) and CLF ('Unidad de Fomento', which is a non-circulating currency that adjusts due to inflation). It would be very helpful to have both available as there are times where deals are billed in CLF and/or CLP.

**Describe the solution you'd like**
The optimal solution, as discussed in this [slack thread](https://lago-community.slack.com/archives/C03MCH55EL8/p1671636495342389) would be to add CLF to the list of supported currencies, having in mind that the Stripe integration would not support it.

**Describe alternatives you've considered**
Open to alternatives.

**Comment by mathieu-lago** [comment]
Thanks for the clear description, @jerosalazar!
As discussed with @jdenquin, I've logged it as an improvement and will let you know when CLF is available.

**Comment by michaelponrajah** [comment]
Hello @jerosalazar, we've just released a new version `v0.19.1-alpha` where you can use the currency `CLP` and `CLF`! 
I'm closing this issue and feel free to reach out in the community if you see any issues. 🙌
