### ISSUE TITLE
Refund a customer?

### ISSUE THREAD

**Issue by sudo-sand** [getlago/lago#168]
According to @mathieu-lago, creating a credit note manually will be a premium feature.

How do I refund a customer on the self-host?

**Comment by sarkissianraffi** [comment]
Hi @sudo-sand, this premium feature will also be available on a self hosted version, gated behind a paying license. If you need more information, don’t hesitate to reach out at hello@getlago.com.

**Comment by sudo-sand** [comment]
So there is no way for me to refund a customer on the self-hosted version?

**Comment by sudo-sand** [comment]
Because refunding is a very fundamental part of the invoicing, not a nice to have feature.

**Comment by sarkissianraffi** [comment]
There is a way to refund customers on the self hosted version, but this is a paying feature. It will be available on the self hosted version. We understand that it’s an important feature, this is why we decided to develop it. However, this feature is going to be a paying one. You can still use it by paying a premium self hosted licence

**Comment by sudo-sand** [comment]
1- You're saying it will be in the self-hosted, but you're saying I will need a premium license to use it.
2- How much is that? Does it offer anything else?

**Comment by sarkissianraffi** [comment]
1- Yes, exactly. We will have 3 different versions of Lago for now. The **self hosted free**, the **self hosted premium** and the **cloud** versions. Both cloud and self hosted premium will have the same feature set.

2- It depends on the volume of usage based events you are sending. We charge a monthly platform fee + overages of usage based events. To know the exact quote for your use-case, don't hesitate to contact hello@getlago.com.

To be clear, a great part of the billing engine we created is and will remain for free. You are able to build a powerful pricing structure with Lago for free, and this will be the case forever (we'll continue to add free features, obviously). However, new features are getting heavy to develop in terms of resources. This means we consider more advanced features, like refunds, as premium features. For now, the list of premium features is the following:
- Credit notes (and ability to perform refunds)
- Timezones (bill on your customers' timezone)
- Grace periods (delay invoice creation to perform adjustments on a past periods)
