### ISSUE TITLE
Q: When I upgrade a customer, a credit note is applied

### ISSUE THREAD

**Issue by sudo-sand** [getlago/lago#170]
Why is there a credit note after a customer getting upgraded?

**Comment by sudo-sand** [comment]
One more thing, https://community.getlago.com/ isn't working for me.

**Comment by sarkissianraffi** [comment]
Hi! 
In this case, an automatic credit note is applied to be fair with the end customer.
Imagine that you paid in advance a $10 plan, and you decide to upgrade to a $100 one. You already paid a part of the first one, so it needs to be deducted from the second payment. 
In our opinion, this is the cleanest way to do it. Do you have another idea for this use case ? 

On top of this, the link you sent has been replaced by getlago.com/slack. Can you tell us where you find an occurrence of this old link please? 

Thanks

**Comment by sudo-sand** [comment]
I found that link in the issues template (https://github.com/getlago/lago/issues/new/choose) 

Does it include the days passed? (upgrading on 28th for example shouldn't be the same as the 5th)
What about a downgrade, is it possible to have the same thing? Immediately downgrade and create a credit note?

**Comment by sarkissianraffi** [comment]
Yes it prorates everything based on the number of days used by the first plan.
However, it’s not possible to do the same for a downgrade as we wanna make sure that a user that has paid for usage based prices at X rate will benefit from it till the end of the period. The downgrade option would work if and only you are using subscriptions. If you add usage based components on top of it, the logic is broken. This is why we wait the end of the period to trigger a downgrade

**Comment by sudo-sand** [comment]
What if I want to only have subscriptions only plans, how would I setup the downgrade? Or is this feature not available? I want the same thing that happens with the upgrade to happen when downgrading.

**Comment by sarkissianraffi** [comment]
For now, this option is not available. It’s not something we planned to work on in a close future because we want to keep consistency for the billing engine and avoid edge cases. Our users are complying with this calculation method and working well for them

**Comment by sarkissianraffi** [comment]
For now, this option is not available. It’s not something we planned to work on in a close future because we want to keep consistency for the billing engine and avoid edge cases. Our users are complying with this calculation method and working well for them

**Comment by sudo-sand** [comment]
Is there a way to enable it or is it not implemented?

**Comment by sarkissianraffi** [comment]
It’s not implemented and we haven’t planned to work on this in a close future.

**Comment by sudo-sand** [comment]
ok. thanks. dont forget to update the link in the issues template
