### ISSUE TITLE
[BUG]: After upgrading/downgrading a subscription, new events are not shown in the usage

### ISSUE THREAD

**Issue by Saleemnestorx** [getlago/lago#171]
**Describe the bug**
After upgrading/downgrading a subscription, new events are not shown in the usage. We are able to see them in event debugger section

**To Reproduce**
1. Upgrade a subscription to anther plan 
2. Get the Id of that external subscription id  and external  customer id 
3. Create an Event using those info 
4. Go to the debugger  in Lago UI to check the event
5. Go to the subscription usage to get usage  

**Expected behavior**

**Screenshots**

**Support**

**Additional context**

**Comment by rsempe** [comment]
👋 @Saleemnestorx 

Are you using the cloud version or Lago self-hosted?

We fixed an issue last week around this, can you verify that you're using the latest version ([v0.19.3-alpha](https://hub.docker.com/layers/getlago/api/v0.19.3-alpha/images/sha256-c5fc7be233710bdb2325e1541def8adaa8f7b6f682965952a5592d7720023c5a))?

We tried to replicate the issue on the cloud version, without success.

**Comment by Saleemnestorx** [comment]
@rsempe 
I am using Lago self hosted .
Those are the steps to replicate :
- Create two plans and set their plan model amount to 0
-  Subscribe  one of the plans to the customer 
- Send an event to this subscription it will be received .
- Upgrade or downgrade to the other plan
- Try to send an event again it will not be counted 
- If you go to the debugger you will find the last event

**Comment by vincent-pochet** [comment]
Hey @Saleemnestorx 

Thank you very much for these details.

We might have an idea of the source of this behavior.

For confirmation, are you sending a timestamp in the payload of the event?
If so, is this timestamp on the second event before or after the subscription upgrade?

**Comment by Saleemnestorx** [comment]
no we are not sending the time stamp in the payload .
