### ISSUE TITLE
[BUG]: PDF Redirect path should a separate web configuration

### ISSUE THREAD

**Issue by irfn** [getlago/lago#175]
**PDF Redirect path should a separate web configuration**
When deploying Lago the pdf download url should ideally be served via a configurable web front. This is so as to put  pdf service behind an ingress [k8s] or a reverse proxy etc. There is only one config for pdf service in API. 

**To Reproduce**
1. Deploy lago behind an ingress / load balancer
2. LAGO_PDF_URL is meant to be an internal url since its accessible to the API
3. in this case I get a redirect to internal url when I click download invoice.
4. the error doesn't happen if client and deployment are in same network.

**Expected behavior**
Allow a new config maybe LAGO_PDF_FRONT_URL which can be defaulted to LAGO_PDF_URL and the redirect should happen to this.

**Screenshots**
![image](https://user-images.githubusercontent.com/7784/212247601-f41d6670-3539-4d16-8b26-a827bbc006b9.png)

**Support**
 - OS: OS independent
 - Browser All Browsers
 - Version Latest

**Comment by irfn** [comment]
guess this may need to move to https://github.com/getlago/lago-api as the url is sent back from a graphql response

**Comment by jdenquin** [comment]
Hello @irfn !

We use the `LAGO_PDF_URL` with a custom domain for our cloud version!
It's behind an Load Balancer and a proxy ingress, we just put our custom domain as value for this env var.

Would this work also for you?

**Comment by jdenquin** [comment]
Hello @irfn, 

You should set the `LAGO_API_URL` env var to be able to access your PDF, it's not linked to the PDF service that is only generating the files, it does not handle the download or front end, it's a pure internal service!

**Comment by irfn** [comment]
@jdenquin Thanks for the answer. will try this out.
