### ISSUE TITLE
[FEAT]: Translate invoice english words

### ISSUE THREAD

**Issue by Herbak** [getlago/lago#177]
**Is your feature request related to a problem? Please describe.**
In France (and I suppose in other non-english spoken countries), it's a legal obligation to deliver a french written invoice. I would like to be able to translate the invoice template.

**Describe the solution you'd like**
A translate of the english words (invoice, from, bill to...). It's a very small amount of words but I can't use Lago if I can't modify the words in french.

**Describe alternatives you've considered**
Generate the invoice by my side before it's possible to do so, but it remove a lot of the benefit of Lago.

**Comment by mathieu-lago** [comment]
Hi @Herbak - thanks for reaching out!

We should start working on this feature very soon (probably next month). Users will be able to select the customer's preferred language and documents (i.e. invoices and credit notes) will be translated accordingly. French will be one of the first languages available. We will let you know when this feature is ready.

**Comment by Herbak** [comment]
Thanks !!

**Comment by mathieu-lago** [comment]
Document locales available: https://doc.getlago.com/docs/api/resources/locales
