### ISSUE TITLE
Ability to delete a billable metric linked to a subscription

### ISSUE THREAD

**Issue by mathieu-lago** [getlago/lago#179]
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).

Once deleted, the corresponding charges will be removed from the plans and from all `draft` invoices.

Deleted metrics will still be included in past invoices (i.e. `finalized` invoices).

**Comment by vincent-pochet** [comment]
This feature as been released with https://github.com/getlago/lago-api/releases/tag/v0.22.0-beta
