### ISSUE TITLE
Ability to create coupons that apply forever

### ISSUE THREAD

**Issue by mathieu-lago** [getlago/lago#181]
At the moment, the `frequency` of a coupon can either be `once` or `recurring`, with a pre-defined `frequency_duration`.

We will introduce a new `forever` value, so that coupons can apply for as long as needed, until they are removed from the customer account.

**Comment by michaelponrajah** [comment]
## `Coupon that applies forever` is now live in production 🎉

### Useful links
[Changelog](https://doc.getlago.com/changelog/coupons-forever)
