### ISSUE TITLE
Ability to create coupons that apply to specific plans

### ISSUE THREAD

**Issue by mathieu-lago** [getlago/lago#182]
At the moment, coupons apply to all plans.

As a user, I want to be able to define the range of plans to which a coupon can be applied.

**Comment by michaelponrajah** [comment]
### We're closing this issue as we're switching tool for feature requests.

Feel free to add your feedback for the team and vote here:
👉 [Limit coupons to plan(s) - Canny](https://getlago.canny.io/feature-requests/p/limit-coupons-to-plans)
