### ISSUE TITLE
[FEAT]: Support for Adyen

### ISSUE THREAD

**Issue by kolaente** [getlago/lago#183]
[Adyen](https://www.adyen.com/) provides payment apis for card and other payments, like Stripe. They are a lot cheaper than Stripe and European-based which may help with compliance.

To me, a big advantage of Lagos could be the ability to switch payment providers and still have easy access to billing solutions. Stripe Billing etc is nice but I'm tied to them with high switching costs once I start to use them.

**Describe the solution you'd like**

Integration of Adyen as a Payment Provider. Right now there is only Stripe available.

**Describe alternatives you've considered**

Stripe

**Comment by mathieu-lago** [comment]
Hi @kolaente - thanks for reaching out!

We currently have two native integrations available: [Stripe Payments](https://doc.getlago.com/docs/guide/payments/stripe-integration) and [GoCardless](https://doc.getlago.com/docs/guide/payments/gocardless-integration). Adyen is also on our radar and should be the next payment integration. It hasn't been prioritised yet but we'll let you know when we start working on this.

**Comment by mathieu-lago** [comment]
Feature planned - see below:

https://getlago.canny.io/feature-requests/p/support-integration-with-adyen
