### ISSUE TITLE
[FEAT]: compile images for `linux/arm64/v8`

### ISSUE THREAD

**Issue by haf** [getlago/lago#187]
**Is your feature request related to a problem? Please describe.**
As a developer utilising your docker images on a M1/M2 Apple MacBook computer, the latest versions of Docker Desktop fails to pull the images by default:

```
❯ docker pull getlago/api:v0.21.0-beta
v0.21.0-beta: Pulling from getlago/api
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Instead a command like

```
❯ docker pull getlago/api:v0.21.0-beta --platform linux/x86_64
v0.21.0-beta: Pulling from getlago/api
...
```

, has to be used.

This also affects my actual core workflow utilising k3d to spawn a local kubernetes cluster when testing the integration of Lago with the rest of the infrastructure.

**Describe the solution you'd like**
Consider cross-compiling to linux/arm64/v8.

**Describe alternatives you've considered**
I haven't yet figured out how to make k8s pull the with platform, but when I figure that out (like the docker platform flag above), I'll be unblocked.

**Additional context**
No.

**Comment by mathieu-lago** [comment]
Hi @haf - thanks for reaching out!

Our engineering team will look into this and get back to you with an update.

**Comment by jdenquin** [comment]
Hello @haf 

We do have `arm64` images on a separate tag and `docker-compose` file.
https://github.com/getlago/lago/blob/main/docker-compose.arm64.yml
https://hub.docker.com/repository/docker/getlago/api-arm64v8/general
https://hub.docker.com/repository/docker/getlago/front-arm64v8/general

Tell me if it works for you!

**Comment by haf** [comment]
Oh I see. Well, the norm would be that the platforms are all pushed to the same image, so it doesn't really solve my use-case, but it's great that it's already cross-compiled!

**Comment by jdenquin** [comment]
We are working on having the same image for multi platforms, it should be ready for next releases!

**Comment by CarlAmko** [comment]
@jdenquin
Any update on this? It's been ~2 months and 6 releases later and it seems the images are still platform named.

**Comment by jdenquin** [comment]
@CarlAmko I'm still facing some issues with `nokogiri` on the `api` side with the "classic" Dockerfile and `arm64` platform.
Putting this on top of my todo!

**Comment by jdenquin** [comment]
It's actually done and will be available for the next release!
