### ISSUE TITLE
[BUG]: Current configuration doesn't work with API subdomain

### ISSUE THREAD

**Issue by sercanov** [getlago/lago#191]
**Describe the bug**
First of all, I don't have much Docker experience. I use Dokku for this sort of things.
I'm trying to run it directly on AWS EC2 instance, similar to production setup with subdomains like; https://lago.example.com and https://lago-api.example.com

Added to .env and forwarded subdomain CNAME's to EC2 Public IPv4 DNS
```
LAGO_FRONT_URL=https://lago.example.com
LAGO_API_URL=https://lago-api.example.com
```

`lago-front` works fine with HTTPS and self-signed certificates installed but `lago-api` doesn't seem to have a nginx/domain configuration. I can't assign a subdomain to it. I also tried to clone frontend ports and volume configuration to API but then it throws port 443 is already in use error.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/10291644/218882201-525eaabd-29bc-4476-8c69-f4d00dc4ca6b.png">

**To Reproduce**
1. Set Front Domain
3. Set Backend Domain

**Expected behavior**
API should serve on `LAGO_API_URL`

**Screenshots**

<img width="702" alt="image" src="https://user-images.githubusercontent.com/10291644/218882352-106e9b35-6772-45f1-9083-73d8c575c52e.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/10291644/218882398-ba001c49-010d-4f9a-8a64-42159b9856f0.png">

**Support**

**Additional context**

**Comment by jdenquin** [comment]
Hello @sercanov 

The nginx configuration is only for the front end, not for the back end!
Environment variables are just declarative for each app to know where to find the defined service, it's not used to serve the services on a custom domain.

For your need, you should use a reverse proxy (ei: Traefik) to serve the API and FRONT on a custom domain, you can take a look on how we use it for our local development environment here : https://github.com/getlago/lago/wiki/Development-Environment.

**Comment by sercanov** [comment]
Alright @jdenquin thanks, I'm playing with Traefik. I'm not familiar with it. Will comment when it works. It may be helpful to add to docs as production config because people will have an API subdomain in the end.

**Comment by sercanov** [comment]
Different subdomains with Cloudflare origin certificate was troubled so I've used `lago.example.com` and `lago.example.com/api` structure. It works with LetsEncrypt and Nginx, without Traefik now.
