### ISSUE TITLE
[FEAT]: Kubernetes helm chart

### ISSUE THREAD

**Issue by braghettos** [getlago/lago#192]
**Is your feature request related to a problem? Please describe.**
I would like to install Lago on a Kubernetes cluster.

**Describe the solution you'd like**
Docker-compose files are already available, it shouldn't be too complicated to write an Helm chart

**Describe alternatives you've considered**
No real alternatives available for Kubernetes.

**Additional context**
Nothing to add here.

**Comment by jdenquin** [comment]
Hello @braghettos

We have some users that have created Helm Charts, I will check if I can publish something during the next week!

**Comment by jdenquin** [comment]
Hello there, 

Thanks to our community, we just created a new repository with a nice base for Helm charts : https://github.com/getlago/lago-helm-charts

Do not hesitates to open issues or PR on it!
