### ISSUE TITLE
[FEAT]: Multi-tenancy (managing organisations and sharing customers)

### ISSUE THREAD

**Issue by brettwillis** [getlago/lago#193]
Consider a scenario where Lago could be used in a SaaS that allows tenants/organisations to take payments from customers (e.g. consider gym memberships):

- Gyms are paying my SaaS.
- My SaaS allows gyms to take payments from their customers (using their own Stripe account for example), and I could use Lago as the "billing engine" for membership payments.
- Therefore each gym customer is a Lago "organization".
- So Lago needs and API for me to create and manage any number of "organizations" (gyms).
- Lago "customers" (customers of the Gym) could potentially be shared by multiple organizations (e.g. a member could go to multiple gyms). A workaround of this is to duplicate customers within each organisation.

So the key missing feature here is an API to automate creation/deletion of organisations, and setting merchant (Stripe) accounts, editing invoice settings etc. I imagine much of this already exists but is not documented.

**Comment by mathieu-lago** [comment]
Hi @brettwillis - thanks for reaching out!

Lago's open-source version is free for organisations that want to automate their billing. However, users must comply with our [AGPLv3 licence](https://github.com/getlago/lago/blob/main/LICENSE), especially when embedding our billing system into their product.

Many companies have contacted us about the use case you described. We are happy to discuss this and try to find a solution that benefits both parties.

If you are interested, please let me know and I'll ask one of the team to contact you.

**Comment by brettwillis** [comment]
Yes, I'm interested, it would be great to talk to someone about it. Thanks.

**Comment by tannerhallman** [comment]
Also interested in this use case. Was there any docs or plans created from a discussion ?

**Comment by mathieu-lago** [comment]
Hi @tannerhallman - this conversation relates to a specific product for which we do not advertise.

If you'd like to discuss further, please send us an email with a description of your use case and some basic information about your company, so that we can assess your needs: hello@getlago.com.
