### ISSUE TITLE
[FEAT]: Joining fees

### ISSUE THREAD

**Issue by brettwillis** [getlago/lago#196]
Some industries that have an oboarding cost like to charge joining fees for subscriptions (a once-off fee a the start of a subscription that must be paid before it starts).

This is currently possible to implement with add-ons using additional logic, but it would be better if it was integrated into the state of the subscription, e.g.:
- Joining fee payment goes on the same invoice as the subscription, and 
- the subscription doesn't go "active" until the joining fee payment succeeds.

**Comment by mathieu-lago** [comment]
I feel like this use case complements your original request about the subscription status/account balance, so I've [added it here as a comment](https://getlago.canny.io/feature-requests/p/subscription-status-based-on-payment-status).

From a product perspective, this ticket should probably be broken down into several features but it's also interesting to see the full picture.

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/subscription-status-based-on-payment-status

Might be covered by this other feature (scoping in progress): https://getlago.canny.io/feature-requests/p/pay-usage-at-beginning-of-period-and-not-end-of-period
