### ISSUE TITLE
[BUG]: Can't view Developers page

### ISSUE THREAD

**Issue by sercanov** [getlago/lago#199]
**Describe the bug**
Having white screen at https://lago.example.com/developers 
Network tab shows https://lago.example.com/api-keys.4b3f2a1d832241abcb52.js `{"status":404,"error":"Not Found","code":"resource_not_found"}`

Inspected the `lago-front` docker container, the JS file exists there but somehow doesn't return to browser. Copied it as `ff.js` and it serves fine. It's weird. I wonder is it some kind of security measure by nginx to filter sensitive files, like `api-key.js` 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/10291644/220914180-0e3bd162-9ac1-41b6-a0f5-7fcd6a47337f.png">

**Support**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Firefox, Safari, Chrome
 - Version [e.g. 22] v0.22.1-beta

**Additional context**

**Comment by mathieu-lago** [comment]
Hi @sercanov - please can you update to Lago `v0.23.0-beta` and let me know if it works?

**Comment by sercanov** [comment]
hi @mathieu-lago unfortunately the same error with 0.23 too.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/10291644/220942481-54443016-41a8-4876-8b55-3b82abd09153.png">

This is the URL btw 
https://lago.artlabs.ai/api-keys.0c0059aa137a091e8fe6.js

**Comment by jdenquin** [comment]
hey @sercanov, do you use the standard nginx configuration or a different one?

**Comment by sercanov** [comment]
yes, it was about the nginx config 😅 it was catching by api container because of missing trailing backslash. thanks!
