### ISSUE TITLE
[BUG]: Can't create plan through API

### ISSUE THREAD

**Issue by iurycksantos** [getlago/lago#203]
**Describe the bug**
Can't create a simple standard pricing plan through the API, any and all attempts return 422 {'properties': ['invalid_amount']}. Tried, float, string, int, you name it. Still returns invalid amount.

**To Reproduce**
1. Git clone latest version from github
2. docker-compose up
3. Create a at least one metric
4. Try to use the /api/v1/plans endpoint to create a plan

Example of the json I am using:
```
data = {
        "plan": {
            "name": plan_name,
            "code": plan_code,
            "interval": "monthly",
            "description": f"Plan for {client_name}",
            "amount_cents": float(price_subscription)*100,
            "amount_currency": "BRL",
            "trial_period": 0,
            "pay_in_advance": False,
            "charges": [
            {
                "billable_metric_id": metric1_lago_id,
                "charge_model": "standard",
                "properties": [
                {                  
                    "amount":'2'                 
                }
                ]
            },
            {
                "billable_metric_id": metric2_lago_id,
                "charge_model": "standard",
                "properties": [
                {                   
                    "amount": '2'            
                }
                ]
            },
            {
                "billable_metric_id": metric3_lago_id,
                "charge_model": "standard",
                "properties": [
                {
                    "amount":'2'
                }
                ]
            },
            {
                "billable_metric_id": metric4_lago_id,
                "charge_model": "standard",
                "properties": [
                {                
                    "amount": '2'
                }
                ]
            }]
        }
    }
```

**Expected behavior**
Should create a new plan, monthly charged, with standard pricing for metric

**Support**
 - OS: win 10

**Comment by sarkissianraffi** [comment]
Hi @iurycksantos, 

On my side, I tried to reproduce but definitely managed to create a plan using the API. Here is my payload (please make sure you use the same quotes at the same place)

```
{
  "plan": {
    "name": "plan_name",
    "code": "plan_code",
    "interval": "monthly",
    "description": "Plan for {client_name}",
    "amount_cents": 100000,
    "amount_currency": "BRL",
    "trial_period": 0.0,
    "pay_in_advance": false,
    "charges": [
      {
        "billable_metric_id": "YOUR__METRIC1__ID",
        "charge_model": "standard",
        "properties": {
          "amount": "1"
        }
      },
      {
        "billable_metric_id": "YOUR__METRIC2__ID",
        "charge_model": "standard",
        "properties": {
          "amount": "2"
        }
      }
    ]
  }
}
```

Here is the plan created on the UI
<img width="1191" alt="Screenshot 2023-03-01 at 14 51 25" src="https://user-images.githubusercontent.com/24354699/222250963-ffb07cde-ef24-4db6-8c21-3ae72f5460e3.png">

Hope this helps. Can you tell me if it works?

**Comment by iurycksantos** [comment]
> Hi @iurycksantos,
> 
> On my side, I tried to reproduce but definitely managed to create a plan using the API. Here is my payload (please make sure you use the same quotes at the same place)
> 
> ```
> {
>   "plan": {
>     "name": "plan_name",
>     "code": "plan_code",
>     "interval": "monthly",
>     "description": "Plan for {client_name}",
>     "amount_cents": 100000,
>     "amount_currency": "BRL",
>     "trial_period": 0.0,
>     "pay_in_advance": false,
>     "charges": [
>       {
>         "billable_metric_id": "YOUR__METRIC1__ID",
>         "charge_model": "standard",
>         "properties": {
>           "amount": "1"
>         }
>       },
>       {
>         "billable_metric_id": "YOUR__METRIC2__ID",
>         "charge_model": "standard",
>         "properties": {
>           "amount": "2"
>         }
>       }
>     ]
>   }
> }
> ```
> 
> Here is the plan created on the UI <img alt="Screenshot 2023-03-01 at 14 51 25" width="1191" src="https://user-images.githubusercontent.com/24354699/222250963-ffb07cde-ef24-4db6-8c21-3ae72f5460e3.png">
> 
> Hope this helps. Can you tell me if it works?

Dawm, I was 2 hours on this. Apparently it was the brackets in properties[ ] causing the error. Thanks!
