### ISSUE TITLE
[QUESTION]:  How to add fixed quota per month based on plan and allow user to buy additional quota

### ISSUE THREAD

**Issue by khanakia** [getlago/lago#209]
I have a plan e.g. Basic and each customer with this plan will bet 5 GB bandwidth every month.

However, they can buy more bandwidth in case their bandwidth is exhausted. 

how do I achieve this?

**Comment by sarkissianraffi** [comment]
Hi @khanakia, is the following use case working for you?

1. Define a billable metric called **Bandwidth**, calculating a sum of `gb`
2. Create a plan (ie: Premium)
3. Offer in this plan an additional usage-based charge, with `graduated` pricing model. First 5 GB are free of charge, any additional tiers come with a price

<img width="1501" alt="Screenshot 2023-03-16 at 15 05 32" src="https://user-images.githubusercontent.com/24354699/225642934-15e16db4-bffe-4f53-83fc-f7d7c89c7bad.png">
<img width="680" alt="Screenshot 2023-03-16 at 15 06 04" src="https://user-images.githubusercontent.com/24354699/225642959-bdac47af-327b-45fe-a59c-061d95dab121.png">

What do you think?

**Comment by khanakia** [comment]
I tried to do something like this already but the thing i do not want to automatically charge users if they go over the bandwidth limit.

I want them to buy another Addon let's say `10 GB Addon` to buy additional bandwidth.

**Comment by sarkissianraffi** [comment]
Ok, so for now, you cannot block when a quota is reached. We just automatically price overage. If you want to set up this behavior, you can take a look at Oso (we partner with them for entitlements) and reach out to Oso's team mentioning that you need it for quotas while using Lago. https://doc.getlago.com/docs/integrations/entitlements/oso
