### ISSUE TITLE
[BUG]: After docker-compose up I got errors about invalid interpolation on clean ubuntu

### ISSUE THREAD

**Issue by EloWeld** [getlago/lago#210]
**Describe the bug**

I followed instructions to setup the Lago but on last command I getting error about env variables or idk.
```
WARNING: The SENTRY_DSN_FRONT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The SENTRY_DSN variable is not set. Defaulting to a blank string.
WARNING: The LAGO_SIDEKIQ_WEB variable is not set. Defaulting to a blank string.
WARNING: The LAGO_AWS_S3_ENDPOINT variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "api": "LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT:-}"
```

**To Reproduce**
git clone https://github.com/getlago/lago.git
cd lago

echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env
source .env

docker-compose up

**Screenshots**
<img width="904" alt="image" src="https://user-images.githubusercontent.com/51724400/226564144-2af11df5-ba28-4f43-a3d4-42bafedfeaeb.png">

**Support**
 - OS: Ubuntu 18.04.6 LTS

**Comment by vincent-pochet** [comment]
Hello @EloWeld 

Thank you for reporting this issue

It looks like we have an issue with the default value for `LAGO_GCS_PROJECT`

Could you try to replace the two occurrences of `LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT:-}` with `LAGO_GCS_PROJECT=${LAGO_GCS_PROJECT}` in the `docker-compose.yml` file and re-run the `docker-compose up` command?

**Comment by EloWeld** [comment]
Thank you for your help! It works after I reinstalled docker-compose using this guide:  https://stackoverflow.com/questions/57456212/error-version-in-docker-compose-yml-is-unsupported

and run docker-compose up with the sudo prefix

Maybe deleting :- helped too

**Comment by vincent-pochet** [comment]
Great! Glad you managed to make it work! :-)
