### ISSUE TITLE
[BUG]: An error occurred, please reload the application

### ISSUE THREAD

**Issue by EloWeld** [getlago/lago#211]
**Describe the bug**
After all container launched in site I see red sign "An error occurred, please reload the application" and can't register

 - OS: Ubuntu 20.04

**Comment by mathieu-lago** [comment]
Hi @EloWeld - please can you share the logs so we can see what the error message is?

**Comment by EloWeld** [comment]
Oh my god, my apologies. I just forgot to properly configure the subdomain for the Lago api. I checked messages in console on a site and catch that front just can't call functions from Lago-api
