### ISSUE TITLE
[BUG]: Credit note created on cancellation of subscription with unpaid invoice

### ISSUE THREAD

**Issue by chendo** [getlago/lago#212]
**Describe the bug**

A customer with an unpaid invoice for a subscription should not receive a credit note when the subscription is cancelled. 

**To Reproduce**

1. Create a Plan (with trial period, unsure if this is important)
2. Create a Customer with no credit
3. Add Plan to Customer
4. Confirm Invoice is created with status Pending
5. Terminate Subscription
6. Customer has a Credit Note for a Subscription they did not pay for

**Expected behavior**
If the Customer hasn't paid the Invoice for a Subscription, they should not receive a Credit Note when the Subscription is cancelled.

**Support**
- Version: v0.26-beta

**Comment by mathieu-lago** [comment]
Hi @chendo - thanks for reaching out!

The behaviour you describe is actually what's expected from the feature. If a plan needs to be paid in advance and the subscription is cancelled during the billing period, the period already completed is due and the fees related to the remaining days may be waived (hence the [credit note](https://doc.getlago.com/docs/guide/credit_notes)).

When the payment status of the invoice is pending, the credit note does not trigger a refund, its amount is added to the credit note wallet associated with the customer account. Therefore, you can either:

- Ask your customer to pay the invoice and refund them the amount of the credit note; or
- Ask your customer to pay the invoice and void the existing credit note if you consider the full period is due; or
- Void the existing invoice by creating another credit note for the period already completed, in which case your customer will not have to pay anything.

Hope this helps. Our team is also [available on Slack](https://www.getlago.com/slack) if you have any other questions.

**Comment by chendo** [comment]
Hmmm, I guess I'm not familiar what is meant to happen, but it felt a bit off as the credit note is effectively applied to account and the customer can resubscribe and have it consume that credit note. If it requires human intervention to avoid a loss in potential revenue, it feels like a bug to me. That being said, I assume the team has done a lot more research into this than I have! Thanks for the quick response.
