### ISSUE TITLE
[FEAT]: Generate Invoice on an event

### ISSUE THREAD

**Issue by LouayTawfik** [getlago/lago#213]
Can the invoice be generated on an event? For example by calling an API?
We might need to issue 2-3 invoices per week. In some cases, we might want to have a daily invoice.

**Comment by mathieu-lago** [comment]
Hi @LouayTawfik - thanks for reaching out! I replied to your message on Canny, so I'll close this issue.

For reference, in case other people are interested in this conversation, here's the [link to the feature request](https://getlago.canny.io/feature-requests/p/can-the-invoice-be-generated-on-an-event).
