### ISSUE TITLE
[BUG]: disabling signup does not actually disable it

### ISSUE THREAD

**Issue by spantaleev** [getlago/lago#220]
**Describe the bug**

Related to https://github.com/getlago/lago/issues/47

Passing `LAGO_SIGNUP_DISABLED=true` to the `front` container makes it **hide** its **Sign up** link, which is good, but it's not enough to actually disable signup.

Disabling signup should be done at the backend level (`api` service) and should **block** GraphQL API requests that attempt to create new users.

All Lago instances which run with  `LAGO_SIGNUP_DISABLED=true` are vulnerable to being attacked with requests like these:

```sh
curl 'https://LAGO_HOSTNAME/api/graphql' \
-H 'content-type: application/json' \
--data-raw $'{"operationName":"signup","variables":{"input":{"email":"somone@example.com","password":"string-password-here","organizationName":"Organization Name Here"}},"query":"mutation signup($input: RegisterUserInput\u0021) {\\n  registerUser(input: $input) {\\n    token\\n    user {\\n      id\\n      ...CurrentUser\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment CurrentUser on User {\\n  id\\n  organizations {\\n    id\\n    timezone\\n    __typename\\n  }\\n  __typename\\n}"}'
```

.. which would successfully create new users. You don't need a pretty UI to do it and hiding the UI is not enough to solve #47.

**Expected behavior**

`LAGO_SIGNUP_DISABLED` should be passed along to the `api` service and it should disable user registration on the backend itself.

Hiding the Sign Up button (https://github.com/getlago/lago-front/pull/236) is only the cosmetic part of the solution. What's more important than this cosmetic part is actually disabling signup.

**Comment by jdenquin** [comment]
@spantaleev thanks for raising it! It sounds more like an enhancement than a bug!
This is exactly what we wanted to have, only the possibility to disable the Signup on the Front end side.

btw we understand the need you can have so we will handle it! Feel free to open a PR and make the change if you want to contribute into it!

**Comment by jdenquin** [comment]
@spantaleev it has been updated in this PR, will be available in the next release : https://github.com/getlago/lago-api/pull/1206

**Comment by larsblumberg** [comment]
> Passing `LAGO_SIGNUP_DISABLED=true` to the `front` container makes it **hide** its **Sign up** link, which is good, but it's not enough to actually disable signup.

For anyone reading this, be aware that the env var nowadays (?) is called `LAGO_DISABLE_SIGNUP` and not `LAGO_SIGNUP_DISABLED`. You may find yourself unintentionally keep sign up enabled by using the wrong env var name.

Sources:

- https://github.com/getlago/lago/blob/3d849f59476285a2159816796daa61cffdbd89ab/docker-compose.yml#L78

- https://github.com/getlago/lago-api/blob/a65e674da2a82eace3ea81a95a6cb0d5e59bdb88/app/services/users_service.rb#L20

```rb
  def register(email, password, organization_name)
    if ENV.fetch('LAGO_DISABLE_SIGNUP', 'false') == 'true'
      return result.not_allowed_failure!(code: 'signup_disabled')
    end
```
