### ISSUE TITLE
[BUG]: Using redis with password does not work entirely

### ISSUE THREAD

**Issue by BirknerAlex** [getlago/lago#223]
**Describe the bug**
I tried to use redis with password, using the `REDIS_PASSWORD` and `LAGO_REDIS_CACHE_PASSWORD` environment variables. This works quite well but when Sidekiq tries to process a Stripe payment when working on the pending invoices a `NOAUTH Authentication required` exception will be thrown. I tried to find the redis connection on the code base but I didn't find it where the password is not passed correctly. All other things working.

**To Reproduce**
1. Use redis server with password
2. Setup lago docker container with following env variables set `REDIS_PASSWORD` and `LAGO_REDIS_CACHE_PASSWORD`.
3. Enable stripe integration with using a test token of stripe
4. Prepare a invoice with at least a amount of 0.50€
5. Ensure a invoice is created and it's in status PENDING
6. Wait until Sidekiq tries to create the Stripe payment
7.  An `NOAUTH Authentication required` exception will be thrown on Sidekiq
8. Invoice stays in status PENDING

**Comment by jdenquin** [comment]
can you give us more information about the way you are using env vars?
All your async jobs are failing or just the one with Stripe?

**Comment by vincent-pochet** [comment]
Hello @BirknerAlex, 

this issue has been fixed today with the release v0.29.1-beta.

It was related to a specific config we have to prevent duplicated payments on Stripe which was ignoring the provided Redis password.
If you update to the latest version everything should work

**Comment by BirknerAlex** [comment]
Thank you for the quick fix! 🥳
