### ISSUE TITLE
[BUG]: application containrs exited with 127 code

### ISSUE THREAD

**Issue by craveqx** [getlago/lago#227]
**Describe the bug**
Get errors when try to start docker-compose.yml

lago-worker  | bundler: command not found: sidekiq
lago-worker  | Install missing gem executables with `bundle install`
lago-worker exited with code 127

lago-api     | bundler: command not found: rake
lago-api     | Install missing gem executables with `bundle install`
lago-api     | bundler: command not found: rails
lago-api     | Install missing gem executables with `bundle install`
lago-api     | bundler: command not found: rails
lago-api     | Install missing gem executables with `bundle install`
lago-api exited with code 127

lago-clock   | bundler: command not found: clockwork
lago-clock   | Install missing gem executables with `bundle install`
lago-clock exited with code 127

**To Reproduce**
1. Go to https://doc.getlago.com/docs/guide/self-hosting/docker
2. Make steps for docker compose run
3. See error

**Expected behavior**
All application run without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/105877802/234694667-d8fcb0fd-8884-4b8c-9f37-062831db13a4.png)

**Support**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Docker version 19.03.8, build afacb8b7f0

**Comment by jdenquin** [comment]
can you confirm that the version of Lago is `v0.29.1-beta` ?
I do not reproduce this error, are you on an `amd64` platform or `arm64` ?

**Comment by craveqx** [comment]
amd64

After update docker up to version 20.10.21, build 20.10.21-0ubuntu1~20.04.2 all containers started. 

Thx
