### ISSUE TITLE
[BUG]: Links are broken under the Developers tab

### ISSUE THREAD

**Issue by nimeshsubramanianv2** [getlago/lago#228]
**Describe the bug**

**To Reproduce**
1. Go to https://www.getlago.com/
2. Click on Developers
3. click on documentation/or other links except for github

**Expected behavior**
We should be able to see documentation or changelog.

**Screenshots**
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/38137978/234923806-067571f5-b30d-4460-8030-7dde3f429a5b.png">

**Support**

**Additional context**

**Comment by sarkissianraffi** [comment]
Everything is working well for us and several people pinged in our community. 
Including for Safari, Chrome and Firefox.
