### ISSUE TITLE
[BUG]: duplicate webhook on multi-addon one-off-invoices

### ISSUE THREAD

**Issue by stephentgrammer** [getlago/lago#239]
**Describe the bug**
I am getting duplicate webhooks whenever I created a new one-off invoice with multiple addons. It didn't appear to happen with normal subscriptions or with a single addon on a one-off invoice.

**To Reproduce**
1. Add a customer
2. Add an addon
3. Add a one-off-invoice to the customer with multiple addons (I added the same addon with different unit prices)
4. Listen for the `invoice.one_off_created` webhook and when it arrives, trigger an api call to download the invoice
5. You should receive another identical `invoice.one_off_created` webhook as well as a `invoice.generated` webhook

**Expected behavior**
Only one `invoice.one_off_created` and one `invoice.generated` webhook

**Support**
 - OS: Ubuntu 22.10
 - Browser: brave
 - Version: 0.33.0

**Additional context**
Note: the second identical webhook does NOT appear in the webhook logs in the lago frontend.

**Comment by michaelponrajah** [comment]
Hey @stephentgrammer, thanks for spotting it, the team is currently working on it. 
We'll keep you posted if we need more context or once a fix has been released 🙌

**Comment by stephentgrammer** [comment]
With 0.34.0, I cannot reproduce this. Thanks guys!
