### ISSUE TITLE
[BUG]: MigrationTaskJob TaskNotFoundError

### ISSUE THREAD

**Issue by stephentgrammer** [getlago/lago#244]
**Describe the bug**
Out of the box run of docker compose on 0.34.3 give a few `TaskNotFoundError`s on `MigrationTaskJob`s.

**To Reproduce**
1. Clone lago
2. Check out commit ad5f7d2

**Expected behavior**
No migration errors? ;)

**Screenshots**
None, see attached logs.

**Support**
 - OS: Ubuntu 22.10
 - Version: 0.34.3
 - Docker Compose version v2.15.1

**Additional context**
See logs:

[migration_exception_logs.txt](https://github.com/getlago/lago/files/11627752/migration_exception_logs.txt)

**Comment by vincent-pochet** [comment]
Thank you very much for pointing it out @stephentgrammer!

Indeed, the `invoices:fill_vat_rate` seems to be missing.
It's not blocking on a fresh install because no former invoices have to be migrated but still it's not ideal...

We will prepare a fix for this issue.
