### ISSUE TITLE
[BUG]: list of currencies has mismatches between names and codes

### ISSUE THREAD

**Issue by sk-** [getlago/lago#250]
**Describe the bug**
The documentation page showing the list of supported currencies has some tabulation issues, meaning some of the codes are showing the wrong name.

**To Reproduce**
1. Go to https://docs.getlago.com/docs/api/resources/currencies

**Expected behavior**
All codes should have the right currency name

**Screenshots**
In the screenshot below:
- CHF should be Swiss Franc
- CLP should be Chilean Peso
- CNY should be Chinese Yen

<img width="445" alt="Screen Shot 2023-06-23 at 17 26 40" src="https://github.com/getlago/lago/assets/911768/d758d9e4-c8c0-4191-9535-c371c608f5e2">

**Comment by vincent-pochet** [comment]
Thank you @sk- for reporting this issue. Indeed the codes and names are mismatching. A fix will be released soon.
