### ISSUE TITLE
[BUG]: GraphQL erro. Field 'totalAmountCurrency' doesn't exist on type 'Invoice'

### ISSUE THREAD

**Issue by noobjam** [getlago/lago#255]
**Describe the bug**
I encountered an error while using our GraphQL API. When I click on the "Invoices" section of our application, the following error occurs: 
```
[GraphQL error]: Message: Field 'totalAmountCurrency' doesn't exist on type 'Invoice', Path: fragment InvoiceListItem,totalAmountCurrency, Location: [{"line":31,"column":3}]
```

**To Reproduce**
1. Log in to the application.
2. Navigate to the "Invoices" section.
3. Click on any invoice to view the details.

**Expected Behavior**
The invoice details should be displayed without any error.

** Actual Behavior**
The error message mentioned above is shown, and the invoice details are not displayed.

Please let me know if you need any additional information to investigate the issue. Any help or guidance in resolving this problem would be greatly appreciated.

Thank you!

**screenshot**
![invoice](https://github.com/getlago/lago/assets/74034851/852c1798-7651-40b8-b642-877e4e694de5)

**Comment by ansmonjol** [comment]
Hello @noobjam, thanks for reporting this.

Can I ask you which version of Lago are you using?

I'm asking because the field `totalAmountCurrency` is not used in our app since `v0.31.0-beta`.

If you're using the last version, it could mean a migration has not been performed correctly on your app and we could dig into this direction.

**Comment by noobjam** [comment]
Hi @ansmonjol ,
About the versions, lago_api:  :v0.38.0-beta, lago_front: :v0.30.0-beta.

**Comment by ansmonjol** [comment]
Thanks for the info.

Both should be on the same version. Don't really understand how you can manage to have different versions on your side 🤔
But indeed, as you're using a version below `v0.31.0-beta` your error "make sense", in a way

If there is a mismatch between versions, you can expose yourself to those kind of issues. 

How do you use Lago app? Aren't you using the [Lago repo](https://github.com/getlago/lago) and download it from there?

**Comment by noobjam** [comment]
first time i downloaded it from the lago repo, but when upgrading i  just edited the compose file for the api services, and missed the front.

**Comment by ansmonjol** [comment]
Ok! Updating the FE app would solve your issue for sure. 

Resolving
