### ISSUE TITLE
[BUG]: Error running it locally - getlago/api:v0.39.2-beta not found: manifest unknow

### ISSUE THREAD

**Issue by daisy1754** [getlago/lago#257]
**Describe the bug**

I encounter error when I try to follow https://docs.getlago.com/guide/self-hosted/docker

**To Reproduce**
follow https://docs.getlago.com/guide/self-hosted/docker

```
# Get the code
git clone https://github.com/getlago/lago.git

# Go to Lago folder
cd lago

# Set up environment configuration
echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env
source .env

# Start
docker-compose up
```

**Expected behavior**
Lagos will start

**Support**
 - OS: Mac

**Comment by daisy1754** [comment]
apparently 39.2 doesn't exist - https://hub.docker.com/r/getlago/api/tags

**Comment by daisy1754** [comment]
manually changed them to 39.1 and it worked

**Comment by jdenquin** [comment]
the `v0.39.2-beta` is now available, sorry for the delay!
