### ISSUE TITLE
[BUG]: deadlink to terms of service and privacy policy

### ISSUE THREAD

**Issue by daisy1754** [getlago/lago#258]
**Describe the bug**
dead link

**To Reproduce**
follow https://docs.getlago.com/guide/self-hosted/docker
open http://localhost/sign-up

see link
https://www.getlago.com/legal/terms-of-service
https://www.getlago.com/legal/privacy-policy
both are not found

**Screenshots**
<img width="758" alt="Screenshot 2023-07-08 at 6 15 04 AM" src="https://github.com/getlago/lago/assets/980077/b603576d-692d-4b78-aa85-e02b189f0b68">

<img width="2054" alt="Screenshot 2023-07-08 at 6 15 15 AM" src="https://github.com/getlago/lago/assets/980077/4084a718-0edb-4deb-b550-3165a6df4fca">

**Comment by ansmonjol** [comment]
Hey @daisy1754, thanks for reporting this.

Those links have been fixed, and the fix will be available in the next release.

In the meantime, you can find them here
- [Terms of Service](https://www.getlago.com/company/terms-of-service)
- [Privacy Policy](https://www.getlago.com/company/privacy-policy)

Please don't hesitate to re-open this issue if the error persists after the next release.
You can also [join our Slack community](https://www.getlago.com/slack) to report bugs or ask any questions.

Have a nice day!
