### ISSUE TITLE
[BUG]: math in volume pricing plan preview is not updated

### ISSUE THREAD

**Issue by daisy1754** [getlago/lago#259]
**Describe the bug**
When I update number in volume pricing, preview number was not properly updated

**To Reproduce**
1. Go to /create/plans
2. Under 'Usage-based charges', add new volume pricing
3. Change unit and per-unit pricing

**Expected behavior**
101 units would cost $301.00 in attached screeenshot

**Screenshots**
<img width="816" alt="Screenshot 2023-07-08 at 6 21 39 AM" src="https://github.com/getlago/lago/assets/980077/3facd13e-f258-4fb3-9cda-778c4ceedca4">

**Support**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest lagos (master) self host

**Comment by sarkissianraffi** [comment]
Hi, 
This calculation is totally correct.
- Volume pricing takes the entire number of units and only assigns it to the tier price it's belonging to. 101 units x $1 = $101

The one you described is the **graduated** pricing model, applying different tiers
