### ISSUE TITLE
[BUG]: can't download invoice pdf.

### ISSUE THREAD

**Issue by noobjam** [getlago/lago#261]
**Describe the bug**
When attempting to download the invoice PDF,I am encountering an "Internal Server Error" message.
Using v0.40.0-beta of lago.

**To Reproduce**

1. log in 
2. navigate to invoices
3. try downloading it

**Expected behavior**
invoice downloaded as pdf.

**Actual behavior**
error message

**Screenshots**

1. Browser response
![browser_response](https://github.com/getlago/lago/assets/74034851/b5be1607-5eb6-4e93-81a3-ddfaee70d7cb)
2. the lago-api logs
![pdf-invoice](https://github.com/getlago/lago/assets/74034851/3f400c1d-5090-4bfa-9971-013477cef155)

**Comment by ericmaro** [comment]
anyone reached here and got confused, all you have to do is to set LAGO_PDF_URL on your docker-compose.yml and make sure the PDF container under lago on docker is running.
