### ISSUE TITLE
[BUG]: private data exposed?

### ISSUE THREAD

**Issue by believe1499** [getlago/lago#262]
**Describe the bug**
I deployed Lago by docker in my local environment, and sign up an account , but i received advertised email from Lago?!
How can you get my local account data?

It is so ridiculous!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Support**

**Additional context**

**Comment by sarkissianraffi** [comment]
Hi,
Everything is described both in the docs and in the read me. You can opt out at anytime. Please don't hesitate to read the documentation and the read me! 

https://docs.getlago.com/guide/self-hosted/tracking-analytics

**Comment by believe1499** [comment]
Sorry for my previous misunderstanding, i will try it, thank you!
