### ISSUE TITLE
[BUG]: Facing issue while setup on docker.

### ISSUE THREAD

**Issue by Haseeb65** [getlago/lago#263]
**Support**
 - OS: Win 10

**Error : exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.**

am using the compose provided in this repo. No container is set upped in docker no process or container is using port 80 

--------------------------------------------------------------------------------------------------------------------------------------------
*************************** LOGS DUMP **************************************

$ docker-compose up
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"REDIS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"SENTRY_DSN\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_SIDEKIQ_WEB\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_AWS_S3_ENDPOINT\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_REDIS_CACHE_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_DISABLE_SEGMENT\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"SENTRY_DSN_FRONT\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"REDIS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"SENTRY_DSN\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_AWS_S3_ENDPOINT\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_REDIS_CACHE_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"LAGO_DISABLE_SEGMENT\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"REDIS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-07-16T14:37:02+05:00" level=warning msg="The \"SENTRY_DSN\" variable is not set. Defaulting to a blank string."
 Container lago-pdf-1  Creating
 Container lago-redis  Running
 Container lago-db  Running
 Container lago-api  Running
 Container lago-clock  Creating
 Container lago-front  Creating
 Container lago-worker  Creating
 Container lago-pdf-1  Created
 Container lago-worker  Created
 Container lago-clock  Created
 Container lago-front  Created
Attaching to lago-api, lago-clock, lago-db, lago-front, lago-pdf-1, lago-redis, lago-worker
lago-api exited with code 0
lago-api exited with code 137
lago-db      | 2023-07-16 09:37:05.915 UTC [1] LOG:  received fast shutdown request
lago-db      | 2023-07-16 09:37:05.946 UTC [1] LOG:  aborting any active transactions
lago-db      | 2023-07-16 09:37:05.946 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
lago-db      | 2023-07-16 09:37:05.947 UTC [22] LOG:  shutting down
lago-redis   | 1:signal-handler (1689500225) Received SIGTERM scheduling shutdown...
lago-pdf-1   |
lago-pdf-1   |   _____     __           __
lago-pdf-1   |  / ___/__  / /____ ___  / /  ___ _______ _
lago-pdf-1   | / (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
lago-pdf-1   | \___/\___/\__/\__/_//_/_.__/\__/_/  \_, /
lago-pdf-1   |                                    /___/
lago-pdf-1   |
lago-pdf-1   | A Docker-powered stateless API for PDF files.
lago-pdf-1   | Version: 7.6.0
lago-pdf-1   | -------------------------------------------------------
lago-pdf-1   | [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook
lago-pdf-1   | [SYSTEM] uno: long-running LibreOffice listener ready to start
lago-pdf-1   | [SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
lago-pdf-1   | [SYSTEM] gc: application started
lago-pdf-1   | [SYSTEM] prometheus: collecting metrics
lago-pdf-1   | [SYSTEM] api: server listening on port 3000
lago-redis   | 1:M 16 Jul 2023 09:37:06.026 # User requested shutdown...
lago-redis   | 1:M 16 Jul 2023 09:37:06.026 * Saving the final RDB snapshot before exiting.
lago-redis   | 1:M 16 Jul 2023 09:37:06.086 * DB saved on disk
lago-redis   | 1:M 16 Jul 2023 09:37:06.086 # Redis is now ready to exit, bye bye...
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by harrisyn** [comment]
@Haseeb65 this means you already have a service running on port 80, maybe another webserver.
You can edit the dockerfile to change the local port binding to something other than 80, maybe 8000, then it should be assessable at localhost:8000

**Comment by Haseeb65** [comment]
@harrisyn I have changed the port to 81, all containers loaded successfully the dashboard is not loading 

Other then using domain, i have also tried localhost. that is also not working

Please check the below images for reference : 

Docker Environment : 
![image](https://github.com/getlago/lago/assets/117621693/978baa2d-1a93-4ae1-a612-39a93c38d609)


Browser Response : 
![MicrosoftTeams-image (2)](https://github.com/getlago/lago/assets/117621693/5ddd9fdf-8a89-47f8-a292-20df2512d76c)

**Comment by harrisyn** [comment]
did you try http://localhost:81

**Comment by Haseeb65** [comment]
@harrisyn Yes i have tried http://localhost:81/ it lands me on **nginx** page, which says if you are seeing this page then nginx is working successfully.

**Comment by harrisyn** [comment]
definitely weird, I don't know much about the internals of Lago, I recently
ran a copy locally and it worked just fine.
also clicking on the 81:80 should open up a browser page, if that still
shows Nginx, maybe you have a different webservice running.

Can't help beyond this point

**Comment by Haseeb65** [comment]
@harrisyn thank you for your time, still struggling with it.
Reconfigured to different ports but still same result

**Comment by vincent-pochet** [comment]
Hello @Haseeb65 ,

Since you have changed the default port for the front-end application, have you changed the `LAGO_FRONT_URL` environment variable accordingly?

**Comment by Haseeb65** [comment]
@vincent-pochet It worked fine

I Just changed the **LAGO_FRONT_URL** to http://localhost/:81 in **docker-compose.dev.yml** file and it worked fine. The dashboard is up 
Thanks brother

but the lago_API which is at http://localhost:3000 is still not working

**Comment by jdenquin** [comment]
hey @Haseeb65 , what do you mean by not working for API?

**Comment by Haseeb65** [comment]
@jdenquin,
Lago’s API is exposed at http://localhost:3000/.
Please check the below screenshot and check their docs at [here ](https://doc.getlago.com/guide/self-hosted/docker)" You can now open your browser and go to http://localhost/ to connect to the application. Just after [signing up](https://doc.getlago.com/guide/self-hosted/docker#signing-up), **Lago’s API is exposed at http://localhost:3000/** "


![image](https://github.com/getlago/lago/assets/117621693/543af453-878a-4d70-9c0e-75981cda7df6)

**Comment by jdenquin** [comment]
So with the front end you can't access to the `api`?
Are you able to sign up?
