### ISSUE TITLE
Give visibility to our user's customers on their current usage

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#27]
## Problem description
User’s customers have a hard time to know how much their current usage is at a T moment and how much they will be charged from it

_How important is this for you?_

**Comment by sarkissianraffi** [comment]
This feature has been released. You can find:
1. The changelog => https://doc.getlago.com/changelog/current-usage
2. The API Ref => https://doc.getlago.com/docs/api/customer_usage/customer-usage
3. The guide => https://doc.getlago.com/docs/guide/customers#displaying-customer-current-usage
