### ISSUE TITLE
[BUG]: Stripe Checkout Url Job Failed

### ISSUE THREAD

**Issue by ulmer-morozov** [getlago/lago#270]
At the customer creation step Lago doesn't send webhook "customer.generate_checkout_url".
But others webhooks such as "invoice.created", "customer.payment_provider_created", "subscription.terminated" are working.

**Error in lago-worker**
> [2023-08-17T14:32:21.648889 #6] ERROR -- : [ActiveJob] [PaymentProviderCustomers::StripeCheckoutUrlJob] [4d6805d0-5d95-4705-95a7-77ff6b851698] [membership/948f0700-d230-49c5-8e24-99194524ae88] Error performing PaymentProviderCustomers::StripeCheckoutUrlJob (Job ID: 4d6805d0-5d95-4705-95a7-77ff6b851698) from Sidekiq(providers) in 18.79ms: ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):

**Steps to reproduce the behavior:**
1. Clean install Lago
2. Add Stripe Integration
3. Create Customer via API with Stripe billing (with sync: true parameter and stripe payment provider) 
4. See error in lago-worker and no webhook "customer.generate_checkout_url" 

**Expected behavior**

**Support**
 - OS: Ubuntu 22.04.1 LTS
 - Lago version: v0.42.0-beta

**Additional context**
currently we are using demo-mode Stripe account

I've checked all environment variables related to signing but had't found anything.
Could you please help me to understand what could go wrong?

**Comment by sarkissianraffi** [comment]
It's working well on my side. Can you test through the UI to make sure?
<img width="1261" alt="Screenshot 2023-08-18 at 13 05 22" src="https://github.com/getlago/lago/assets/24354699/38f338a2-56f2-4ec3-8d1f-131b4d3dc22e">
<img width="1033" alt="Screenshot 2023-08-18 at 13 05 35" src="https://github.com/getlago/lago/assets/24354699/1d6e111a-6e30-437b-b4d4-0f35fb9b27b2">

**Comment by sarkissianraffi** [comment]
Have you added both  `"sync": true` AND `"sync_with_provider": true` in `billing_configuration`?

**Comment by ulmer-morozov** [comment]
@sarkissianraffi yes, I used those parameters via dotnet client. And also I checked Stripe and everything is ok. Stripe got new customer with Lago metadata and Lago got customer with Stripe id.

```csharp
var customerInput = new CustomerCreateInput(
            customer: new CustomerCreateInputCustomer(
                externalId: workspaceId.ToString(),
                email: email,
                name: email,
                country: countryCode,
                currency: Currency.USD,
                billingConfiguration: new CustomerBillingConfiguration(
                    sync: true,
                    syncWithProvider: true,
                    paymentProvider: PaymentProviderEnum.Stripe,
                    providerPaymentMethods: new List<string>() { "card", "sepa_debit" }
                )
            )
        );
```

**Comment by ulmer-morozov** [comment]
<img width="1491" alt="image" src="https://github.com/getlago/lago/assets/7135845/21309d88-e53c-48e1-99c2-eef80c5c1298">
<img width="758" alt="image" src="https://github.com/getlago/lago/assets/7135845/b5923774-4fd8-4d6a-a772-cd636a839b9c">

I've tried to add customer manually through the UI, checked "Create automatically this customer in Stripe" but new customer haven't appear at Stripe dashboard. On the other hand when I'am creating Customer from code everything works well except "customer.generate_checkout_url" webhook

**Comment by sarkissianraffi** [comment]
In that case you haven't connected the right stripe API Key. Make sure you use the secret key, starting by "sk".

Then go to Lago > Settings > Integrations > Stripe, and paste this secret key

**Comment by ulmer-morozov** [comment]
Before that problem with checkout URL, we got 0.38 version where we couldn't even bind Lago and Stripe. But we got same logs with something about ActiveRecord::Encryption/Decryption

**Comment by ulmer-morozov** [comment]
I've checked the key and it was starting by "sk". And also I think in case of the wrong key Lago wouldn't automatically create customer in Stripe.

**Comment by sarkissianraffi** [comment]
I am not reproducing it tbh, everything is working well on our side. 
By using the API, the customer's created in Stripe dashboard, but not when using the UI?

**Comment by ulmer-morozov** [comment]
I've just tried to remove the integration key and place it again, then removed customer from both Lago and Stripe and everyting is synced. But no webhook for checkout URL

<img width="1728" alt="image" src="https://github.com/getlago/lago/assets/7135845/cb30928a-baaf-4258-b2fa-925936bcec5f">

<img width="1490" alt="image" src="https://github.com/getlago/lago/assets/7135845/43b4a315-ca7e-4e0f-912b-bda7831b5a70">

**Comment by ulmer-morozov** [comment]
> I am not reproducing it tbh, everything is working well on our side.

I am pretty sure It could be problem with wrong setup. May be something wrong with environment variables.

> By using the API, the customer's created in Stripe dashboard, but not when using the UI?

yes

<img width="744" alt="image" src="https://github.com/getlago/lago/assets/7135845/27b780e0-17fe-4c1f-80d8-0525d9b5076e">

**Comment by ulmer-morozov** [comment]
worker logs:

> I, [2023-08-19T12:14:31.883755 #6]  INFO -- : Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job 4eeb5c5362bdf61a4f7b6e9d
I, [2023-08-19T12:14:31.894273 #6]  INFO -- : fail
W, [2023-08-19T12:14:31.894393 #6]  WARN -- : {"context":"Job raised exception","job":{"retry":0,"queue":"providers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Invoices::Payments::StripeCreateJob","args":[{"job_class":"Invoices::Payments::StripeCreateJob","job_id":"6e79796b-3b7d-4942-92c9-0ba20db1a949","provider_job_id":null,"queue_name":"providers","priority":null,"arguments":[{"_aj_globalid":"gid://lago-api/Invoice/562793de-2309-4772-932f-c89b9dc4a502"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2023-08-19T12:14:31Z","tracing_info":{"membership":"membership/948f0700-d230-49c5-8e24-99194524ae88"}}],"jid":"4eeb5c5362bdf61a4f7b6e9d","created_at":1692447271.849512,"enqueued_at":1692447271.849597},"_config":"#<Sidekiq::Config:0x00007f85d6c6f4b8>"}
W, [2023-08-19T12:14:31.894431 #6]  WARN -- : ActiveRecord::Encryption::Errors::Decryption: ActiveRecord::Encryption::Errors::Decryption

**Comment by ulmer-morozov** [comment]
and 

> E, [2023-08-19T12:14:28.872521 #6] ERROR -- : [ActiveJob] [PaymentProviderCustomers::StripeCheckoutUrlJob] [6f381a43-97c9-4e71-977d-d185935d3a00] [membership/948f0700-d230-49c5-8e24-99194524ae88] Error performing PaymentProviderCustomers::StripeCheckoutUrlJob (Job ID: 6f381a43-97c9-4e71-977d-d185935d3a00) from Sidekiq(providers) in 22.56ms: ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):

**Comment by ulmer-morozov** [comment]
I will be glad if you could show me where should I look to diagnose those Encryption/Decription errors.
Oh, sorry, I forgot to mention that I'am using self hosted version of lago in docker containers.

Regardless my problem with Stripe I want to thank you for your job. Lago is the very smooth and clean web service!

**Comment by ulmer-morozov** [comment]
We've fixed the problem by upgrading to Lago version: v0.44.1-beta. We also used new signing credentials generated by `bin/rails db:encryption:init`
