### ISSUE TITLE
[BUG]: unknown attribute 'external_salesforce_id' for Customer when trying to create a customer in fresh build

### ISSUE THREAD

**Issue by thedewpoint** [getlago/lago#271]
**Describe the bug**
Cloned Lago repo and ran using instructions. Created a few plans. Went to the customer screen and attempted to create a customer, got an unknown error. Checked the console and saw error: unknown attribute 'external_salesforce_id' for Customer

**Expected behavior**
customer is created

**Comment by thedewpoint** [comment]
interestingly if i use the api directly i was able to create one although i still saw relevant errors in the console

**Comment by jdenquin** [comment]
Hello @thedewpoint 

Can you pull the repo and do this command : `docker compose exec api rake db:migrate` ?
It should fix your issue!
