### ISSUE TITLE
Generate invoices in PDF

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#28]
## Problem description
Users can’t send invoices to their customer right now. They have to build a PDF system to send invoices or send it to another provider to use the JSON provided from Lago

_How important is this for you?_

**Comment by sarkissianraffi** [comment]
This feature has been released. You can find: 
1. The changelog => https://doc.getlago.com/changelog/download-invoices
2. The API endpoint => https://doc.getlago.com/docs/api/invoices/download-invoice
3. The API guide => https://doc.getlago.com/docs/guide/invoicing/download-invoices
