### ISSUE TITLE
[BUG]: Get error in customer usage tab

### ISSUE THREAD

**Issue by craveqx** [getlago/lago#280]
**Describe the bug**
Hello. I have c# client that make http request to lago API. My application send 2 billable metric events (aggragation type COUNT UNIQUE) at same time (in event debugger same time). After this events lago stop show customer usage for this billing plan. Instead it display error (screenshot bellow).

In Developer event tab recorded two events that has different transaction_id, different properties and same time. (screenshots bellow)
In lago docker-container recorded error after load usage for customer :

```
lago-api  | F, [2023-09-08T16:05:50.996621 #13] FATAL -- : [2e305484-4f89-413b-b031-7212a4c467de]
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] TypeError (can't convert nil into BigDecimal):
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de]
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/billable_metrics/aggregations/base_service.rb:66:in `BigDecimal'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/billable_metrics/aggregations/base_service.rb:66:in `handle_in_advance_current_usage'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/billable_metrics/aggregations/unique_count_service.rb:13:in `aggregate'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/fees/charge_service.rb:99:in `compute_amount'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/fees/charge_service.rb:56:in `init_fee'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/fees/charge_service.rb:46:in `init_fees'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/fees/charge_service.rb:30:in `current_usage'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/invoices/customer_usage_service.rb:71:in `block in add_charge_fees'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/invoices/customer_usage_service.rb:68:in `add_charge_fees'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/invoices/customer_usage_service.rb:44:in `block in compute_usage'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/invoices/customer_usage_service.rb:36:in `compute_usage'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/services/invoices/customer_usage_service.rb:26:in `usage'
lago-api  | [2e305484-4f89-413b-b031-7212a4c467de] app/graphql/resolvers/customers/usage_resolver.rb:18:in `resolve'
```

**To Reproduce**
1. Parallel send two api billiable metric events with aggregation type count unique
2. Click on Customer usages
3. Expand usage 

**Screenshots**
![image](https://github.com/getlago/lago/assets/105877802/092e2a58-2395-4649-acb8-fc86ffc99634)
![image](https://github.com/getlago/lago/assets/105877802/0e542735-1e48-4df3-bef2-f9355c3953e8)
![image](https://github.com/getlago/lago/assets/105877802/903d18d1-d320-47ad-a3ff-9b803e46ad9b)

**Comment by sarkissianraffi** [comment]
Which version of the app are you using?

**Comment by craveqx** [comment]
v0.45.0-beta

**Comment by craveqx** [comment]
After subscription period end and new period start, customer usage work fine. Do you reproduce bug ?

**Comment by jdenquin** [comment]
@craveqx what is your billable metric type? how did you configured it?

**Comment by craveqx** [comment]
Aggregation type : count unique 
Property to aggregate : ItemId 
Type : Recurring

**Comment by lovrocolic** [comment]
@craveqx Can you please try our latest version? This part has been improved recently

**Comment by craveqx** [comment]
Yes, after upgrating bug not reproduced. thank you

**Comment by jdenquin** [comment]
thanks for your return @craveqx , I close this issue so!
