### ISSUE TITLE
[BUG]: Freshly pulled and installed, but can't signup

### ISSUE THREAD

**Issue by vogt31337** [getlago/lago#284]
**Describe the bug**
Hi, I'm new to lago and wanted to check it out. Running Docker Desktop on Windows 10 >22H2

**To Reproduce**
1) docker-compose up (as described in the documentation and all steps before)
2) Trying to signup.

**Expected behavior**
Signup should work

**Screenshots**
![grafik](https://github.com/getlago/lago/assets/7427820/c6807663-774b-4e1b-ae9e-c2c4108ccbbb)

**Support**
 - OS: Windows 10 22H2
 - Browser: Firefox 115.3.0esr
 - Version: newest?

**Comment by aca123321** [comment]
going by the undefined table errors, the db might not have been created

**Comment by jdenquin** [comment]
@vogt31337 it seems that the DB is not created or migrated, can you try to run a `docker compose run api rake db:setup`

**Comment by vogt31337** [comment]
@jdenquin now it's working! Thanks for your help, maybe you could attach this to your documentation?

**Comment by jdenquin** [comment]
Yes I will update it! thanks!
