### ISSUE TITLE
Create prepaid credits system (consumed down and potentially rolled over)

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#29]
## Problem description
Our users can not map their pricing correctly as Lago is not providing the prepaid credit system in the application

_How important is this for you?_

**Comment by packetlost** [comment]
Top Issue for me! <3

**Comment by michaelponrajah** [comment]
Hey @packetlost 👋 
We’re actually working on the feature `prepaid credit`, and I saw it’s a feature that you actually need.

👉 By any chance, do you have 15' min to
1. discuss about your need; and
2. present you the prototype of the experience ?

My calendar is pretty free so tell me what suits you the best, you can reach me at michael@getlago.com

**Comment by packetlost** [comment]
I am seeking to remove Amberflo from the design of an API gateway. I love
what you are doing with Lago; disruptive. The only issues that I see are
the prepaid credits and the scantness of integrations;
 Stripe, Lambda, aws cognito. I feel like Lago is a perfect drop-in
solution for API metering as a Lambda function or Lambda Layer.

PS
For the record, the second that I saw the term "rent-seeking" I knew that
you were on the side of your users.

**Comment by chendo** [comment]
@michaelponrajah our system also uses a prepaid credit system and we would like to move to Lago. Happy to chat about needs and the like. Should I reach out by email as well?

**Comment by michaelponrajah** [comment]
Hey @chendo thanks for the interest and sharing your knowledge, you can reach me by email of course, in // @mathieu-lago will reach you on twitter also to share contact if email is not the best channel! 🙏

**Comment by michaelponrajah** [comment]
## `Create prepaid credits system` is now live in production 🎉

### Useful links
[Documentation](https://doc.getlago.com/docs/guide/prepaid_credits)
[Changelog](https://doc.getlago.com/changelog/prepaid-credits)

**Comment by sarkissianraffi** [comment]
@chendo @packetlost This prepaid credits feature is now live! 🔥 We can jump on a quick call if you need 🤙
