### ISSUE TITLE
Add Gauge model as an billable metric aggregate type

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#30]
## Problem description
Users with a pricing model requiring to calculate usage based on time (e.g. gigabyte per hours) can't use Lago as it's not handling this aggregation type for now.

_How important is this for you?_

**Comment by mtews** [comment]
When I understand it correctly, this would be important for charging support hours as well, right?

**Comment by srelf-eschercloud** [comment]
+1 for this.
Our use case is OpenStack it has the ability to emit events on change (if an instance is created/Deleted/Modified) ideally we would like to be able to pass these messages into an aggregation that can then rate them based on the number of seconds/mins/hours/days etc.

**Comment by michaelponrajah** [comment]
We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Gauge model as aggregation type - Canny](https://getlago.canny.io/feature-requests/p/add-gauge-model-as-an-billable-metric-aggregate-type)
