### ISSUE TITLE
[BUG]: Error 500 when trying to download invoice

### ISSUE THREAD

**Issue by MyWay** [getlago/lago#308]
**Describe the bug**
When trying to download the invoice from the dashboard, I get: 500 Internal Server Error

Payload sent from network tab:
`{"operationName":"downloadInvoiceItem","variables":{"input":{"id":"3dcefbdf-a8b9-4e75-8cd7-bab2be4b09b9"}},"query":"mutation downloadInvoiceItem($input: DownloadInvoiceInput!) {\n  downloadInvoice(input: $input) {\n    id\n    fileUrl\n    __typename\n  }\n}"}`

**To Reproduce**
1. Go to Customer's invoice detail
2. Press **Download invoice**

**Expected behavior**
Download should start.

**Support**
 - Browser chrome
 - Version latest

**Additional context**
Others buttons such as **Update payment status** are working fine.

**Comment by vincent-pochet** [comment]
Hello @MyWay, thank you for reaching out with this issue.

Could you confirm that:
- The pdf container is up and running
- The LAGO_PDF_URL environment variable is set and point to the running instance of the pdf service

**Comment by vincent-pochet** [comment]
Related to https://github.com/getlago/lago/issues/261

**Comment by MyWay** [comment]
You are right, my container was down. Thanks.
