### ISSUE TITLE
[BUG]: ENV Vars not read anymore

### ISSUE THREAD

**Issue by marcelgoya** [getlago/lago#309]
Hi, I've followed the instructions in the docs and installed from the latest git repo. For whatever reason the following env vars are not being read anymore:

- LAGO_FRONT_URL
- LAGO_API_URL

My .env file looks like this:

```
LAGO_RSA_PRIVATE_KEY="xyz"
LAGO_API_URL=https://lago-api.domain
LAGO_FRONT_URL=https://lago.domain
```

**Comment by jdenquin** [comment]
Hello @marcelgoya,

Can you try to specify your `.env` file to docker compose manually?

**Comment by jdenquin** [comment]
@marcelgoya any updates?

**Comment by sjanaX01** [comment]
Where I found LAGO_RSA_PRIVATE_KEY
My env file look like this 
TEFHT19SU0FfUFJJVkFURV9LRVk9XA0Kb3BlbnNzbA0KZ2VucnNhDQoyMDQ4DQo=
䅌佇剟䅓偟䥒䅖䕔䭟奅∽卌琰卌䌱啒䩤楔兂歕坬噑䙒䕉䙴南琰卌琰歃䨱啓㉖啕䍬啑䉒歔湊㍡潆㉡䡬塏督歑剆啒䉚儊乖兄瑫摪搲啮瀲婂嘰兂㥗兊䙫兒㔰啑䙔佃灗其䉘䵏猲坋䩖呗䈱卪桄敬㕕乖汖却啔嘱么਱㍌偒歎塴呕䵨こ㑫䕕瘱浤慰䡗塰䕢ば湍癕㍌䥬䝚坎塡瑆浔㉙呍䵤兢穯坎公䍡夹此祸坍㑍圊䥗儵䙘捺噬乫灈丶歫匵㥓慯搰佡噘娲汇奘䔲乲䘲噇瑭婵桺剺乭嘲奺摺噮摅琲䍏䙮佪剈ੳ坡偨汔坒坍穑啤坎䡓㕎㉚硯啒佒啒ㅖ䡏噚浤歊問瑤㍌祫湗㕎啑眴啢㉉㉎䭬歑刵問桒坒䱤䬊眰䵋㤰儳挱刳摪刱剺奷䘲丶瑩婆婪捗ㄲ䰰䘲佉睇唳汆児灘匴瑇久硇嘰杗临栲剱丱卂䥕੸歙䱨浙䡒䙓兒兎橰浔桒㉋癙汣ぉ穎畨す汖啖坨湗䱨䙒睎つ獚㉕祊汙䍬䕓牰啖橨䙡华坤塊刊婖兪䙫䵂瑹其㥓呅䩕但乆䍂剭扶䉺扐䥬兺摗兎䙫剂乕婮嘰剂摇兇䥖挴硗呉捈圴㕇乇㥹੫坣祳坡半汣䕰止ㅸ㉓㍊䍍ㅴ湡湰浒げ汗䭁浔䩎㍑癎す㔴橍湎呗坆污硅啓睤啥汖䕣济㍣硚攊婆戵娳坮硗婪婗䵗䙭創啬攴瑃噱婖呖噆剪㕇先杗匴灁婬摅扌䥫匰娰敉㥭扨瀰婯啖捷㥹ਲ噚噬啍歸塗䙂啤灤呔㍧呢䝎啥牙汑湖ち浸ㅎ獊啍瘸さ䡴䕗㑣䡡卖汃偖啣䥴湒䡚㉣牧浥婤挊䩗䵭䘱䵪䩖佐䩘敳䉘兒噬卮䕈唵硗到䙄摴杭䬴到䵈奕刵硕敍䙫摶婔䵭捖头䅬啋㡃佷乗ੌ䑤䡖㍔癍坍㕨啔䭎噏佊㉙䡴噕桬啍祆祔䵴穤畨䑕䑊䍥䠹橒ぉ䕢䨵祒娹䡣と汢硊㉚㕰呙慨䴊灷扗栲啬氳啕䙄娱桪坱㑫奷桪卺唳䴲乫捄㥓乶㥭協䉮乨摖䭹䈱䵍䘱兌摭剒婅匲噘摇娳੯歖㕚㉡㍳噡䥰歃㉑㉚瘸ご䜱橎求噕求穖ㅬ汣㕎㍢䩆穎橊䡍積䑍㍍啢㍧湢穨呏㕊呣癉噢湤愊䘲乭㥅啴㥭敊桇卅噺兘䥔剋摖摈ㅕ䱱䉺戴剕挳嘰捏噺愵栳刳案扮摫攱瑭乚剕噺桘摳兘ਲ啢䝸䑕塚㉖㕷汣䭆汑奊塍婰䙔祂ぎ呤杒㍰噎橆䕕癚㍡婆䑤瑚坙告噣奎呖硖橒啤啕䍴ㅚ䑆䴊䩪乺䥫失噬慇桄扱瑗啔ㅅ噓琰捨桘噆瑗剃噪啌乫䍩乫婲剬䵷䈳摷㥃呵硅捯啖搱剔奡歔ਰ坢祰穎啂ㅖ㉑塓浖济票ㅔ㑉啔䤱噏癅噑祉㍒㑣歓稸塗祣浢㑑啡䭧汒獬塓㍯塖灬橚湊䕚䑖娊䉄䵖婈卶栱噋䙭兓嘱䴶剺攵汔剉汮地噖摆汅敶䙕兂婖奩䴰呷嘲匴䩇扪摈婱潷卷么佱乄੪穡㍂こ湊㉒印䡍䍨ㅙ穕坓㍙歚灴楤穳浓浴䡗婤汓䍊浣啒㍎ㅬ湎硨塎䱂䝚癯橔䡤䕔䠹䕖稸䌊摫奮灬兺婪摱嘰慲婕䱅䨰兡瀲丱摗慺し匴乫乷䩭摯噭摺婘卯㤰摴硅噪婆呉硗敇汫䱍砲ਵ䝍䙚湒ㅨ啢䭉㉙乬ㅍ坚穒灎㉋慰䡕牙䕚牙䡗ㅉ橖獊歔ば呣㍉正牅歎湤こ啰㍢すさ乚浕慊刊䩇䵉刲兆決扂搰卂桄婴潧挵眰刱瀲削摮婫婇捪瀱卷剘䴳䩆䰱氱奸栲搵噺婆決剙奪噶㥩ੵ单剴穓党䙓塆坓䍴啑䕰歍睷呑䡖坣㍊湃㍰ㅔㅚ湚㑤橍低湒祚湗䕆䝒祷歗で㍓䭨䑏但呑博圊䥫䱶䨳串䙫婊摕收婭攱摈呈乇䵅瑇剫挲娲氲敳䕫卋瑭扸䙪䵗剔啄㥅摨剪佗婅捓桔奎乕੕汥げ噕穰呥桎䕎䰹䝣乒㉑婤啒潆問煖浥硳浡㕯浒䕚䕣丵汒ㅧ䅕䉰歕䉆塎穧啙䝚䡚睎汎㕒唊䙫啸瑭坸摭唲硇捊㥇奷摔佫摕呌䙺啙噅捰䘲才朳䴱剭呲剭婍婬捖噭奖㥗䍷摭乮噖䵌摪ੲ㉌睯噤汚污塊湑汖䙖偒䡗ㅑㅤ瑆汓ㅚ坣㌸㍔牨浤瑨䝎䐵䝓䕒湍穎塡硣湤奤坥慒䝔畎ㅍ䭍吊㕕佨剅捅䨱摇䙖呇䩺慩瑕估桘嘲䅺䌹ど䱴こ剴㕕䥅䉆卓婖噂啅卧嘰䱚こ䱴こ≋䰊䄀䜀伀开刀匀䄀开倀刀䤀嘀䄀吀䔀开䬀䔀夀㴀∀∀ഀ਀䰀䄀䜀伀开刀匀䄀开倀刀䤀嘀䄀吀䔀开䬀䔀夀㴀∀∀ഀ਀䰀䄀䜀伀开刀匀䄀开倀唀䈀䰀䤀䌀开䬀䔀夀㴀∀∀ഀ਀

And when I run this command 
echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env

I found this error on my windows powershell
base64\ : The term 'base64\' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:53
+ ... cho "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (base64\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


so I run this command 
echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64"" >> .env

So What can I do??

**Comment by jdenquin** [comment]
@devilcoder01 you should run this command on a linux base, powershell does not has base64 command

**Comment by sjanaX01** [comment]
> @jdenquin

I run this on my wsl but I can't open it on my browser. I can't find any url
![Screenshot 2024-02-10 113910](https://github.com/getlago/lago/assets/112236564/bbe94341-bd46-474f-b9b4-f8b6b8a26062)

**Comment by jdenquin** [comment]
@devilcoder01 wsl should expose docker on `localhost` on Windows, is `http://localhost` working?

**Comment by vincent-pochet** [comment]
@marcelgoya Do you still have this issue?

**Comment by vincent-pochet** [comment]
Closing this PR as it has been inactive for a long time.
