### ISSUE TITLE
[BUG]: using docker-compose edit invoice settings of organization not possible

### ISSUE THREAD

**Issue by grafjo** [getlago/lago#310]
**Describe the bug**

running `docker-compose up -d` for 1st time and it's not possible to edit invoice settings of a newly created organization.

**To Reproduce**
* `docker-compose up -d`
* wait some time
* register new user
* go to http://localhost/settings/invoice
* settings are not editable and an error is shown, that something is wrong
* looking into the api logs, you'll notice that at field `eu_tax_management` is nil on customer object
* `docker-compose down`
* `docker-compose up -d`
* wait some time
* now it's working

**Expected behavior**
everything works with a single `docker-compose up`

**Support**
 - using this lago revision with main branch and revision ea4ca762d701396ffdcb4a32875821ef60e60960

**Comment by sofianegargouri** [comment]
Getting the same issue on customer creation:
```
NoMethodError (undefined method `eu_tax_management' for #<Organization
```

**Comment by vincent-pochet** [comment]
Hello @grafjo and @sofianegargouri, it looks like a missing database migration.

We will investigate to figure why this migration takes some time to perform. In the meantime, a workaround is to perform the migrations manually on the running `api` container:
```bash
docker-compose exec api rails db:migrate:primary
```

**Comment by grafjo** [comment]
@vincent-pochet thx for your help, running the migration via rails is is fixing the issue for now

**Comment by vincent-pochet** [comment]
Fixed with https://github.com/getlago/lago-api/pull/1589
