### ISSUE TITLE
[BUG]: Documentation about invoice creation on multi-subscription customers

### ISSUE THREAD

**Issue by grthr** [getlago/lago#321]
The docs state "It is possible to link to the same customer subscriptions that are based on different billing cycles (e.g. a subscription based on calendar dates and another based on the anniversary date)."

The following questions are kept open:

1. How exactly is this case handled? Is there still a single invoice per customer?
2. When are invoices created if the billing periods differ?
3. Is it possible to control the behavior?

**Comment by mathieu-lago** [comment]
Hi @grthr - thanks for reaching out. Regarding your questions:

1. Invoices are automatically consolidated when subscriptions renew at the same time (e.g. all subscriptions are based on calendar billing, or subscription based on calendar billing + subscription based on anniversary billing with anniversary on the 1st). If a subscription renews on the 1st and another on the 5th, invoices won't be consolidated;

2. Invoices are either created on the first day of the period (calendar billing) or on the anniversary of the subscription;

3. The default logic for invoice consolidation cannot be overridden.
