### ISSUE TITLE
[BUG]: docker prod and dev setup

### ISSUE THREAD

**Issue by jtagcat** [getlago/lago#323]
I wanted to demo, see around.

docker-compose.yml did not work. No sample .env. Registering points to missing SQL, db isn't initialized.

[HSTS preloading](https://hstspreload.org/?domain=lago.dev) your dev site is a bad idea. Firefox doesn't compute, Chromium halts with the multi-domain setup soon as well.

**Comment by jdenquin** [comment]
If you can give us some details about whats going wrong we can help, for now.
There is no need for a sample .env, everything needed is in the `docker-compose.yml` file.

**Comment by jtagcat** [comment]
- docker-compose.yml is not functional. Got errors while registering user, logs pointed to missing DB schema, and indeed, compared to `docker-compose.dev.yml` it doesn't include `./pg-init-scripts:/docker-entrypoint-initdb.d`
- *.lago.dev can't be used.
   - Remove the domain from HSTS preload
   - or what I did: `s/lago.dev/lago.bev/g'
- If no `.env` is needed, point it out.

**Comment by jdenquin** [comment]
- I just tested again a fresh install with `docker-compose.yml` and everything looks fine on my side, whats the error you face?
- https://github.com/getlago/lago/wiki/Development-Environment if you want to play around with the dev env
- https://doc.getlago.com/guide/self-hosted/docker
