### ISSUE TITLE
[FEATURE]: latest tag on Docker

### ISSUE THREAD

**Issue by MyWay** [getlago/lago#324]
Could you please add 'latest' tag for docker images?

**Comment by jdenquin** [comment]
yes but we do not recommend to use it!

**Comment by vincent-pochet** [comment]
Hello @MyWay, as mentioned in [the documentation](https://doc.getlago.com/guide/self-hosted/docker#version), we do not recommend to use the latest tag.

The reason behind this is that it does not offers a secure way to manage update and data migration.

I'm closing the issue as we have no plan to change this behavior for now
