### ISSUE TITLE
[BUG]: https://community.getlago.com/ is down

### ISSUE THREAD

**Issue by dorianmariecom** [getlago/lago#327]
**Describe the bug**

The forum is down

**To Reproduce**

1. Go to https://community.getlago.com/

**Expected behavior**

I see a forum

**Screenshots**

![Screenshot 2024-02-22 at 19 41 48](https://github.com/getlago/lago/assets/58794487/7cbeec86-d1fc-466a-af9e-8e396e96c245)

**Support**
 - OS: Darwin Dorians-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 arm64
 - Browser: Chrome
 - Version: Version 121.0.6167.184 (Official Build) (arm64)

**Additional context**

I found the link in the CONTRIBUTING.md

**Comment by sarkissianraffi** [comment]
Hi, this page does not exist anymore, as we are using Slack as a community support tool. Can I ask where you found the link?

**Comment by sarkissianraffi** [comment]
Thanks, this page does not exist anymore as we are using Slack as a community tool. I will remove this link

**Comment by sarkissianraffi** [comment]
Just created a PR to update the link. If you have any questions, please reach out here: https://www.getlago.com/slack

**Comment by dorianmariecom** [comment]
Oh okay thanks
