### ISSUE TITLE
[BUG]: Wrong unit used in calculation for `Weighted Sum` Recurring metric. i.e `0.6466477675381944` instead of `1`.

### ISSUE THREAD

**Issue by AyushChothe** [getlago/lago#339]
**Describe the bug**
When I send an event for 1 unit, the dashboard shows 0.65 units but in the Lago database it is 1 unit.

**To Reproduce**
1. Create a Billable Metric `Volume`
2. Add it to a Plan 
3. Assign the Plan to a User
4. Send the event to the subscription
 ```bash
{
  "event": {
    "transaction_id": "01HV6D9E1Z7CE0FCPFP1W6JNB12",
    "external_subscription_id": "ad899cae-03e6-4bde-b56a-b39b16bd56ed",
    "external_customer_id":"6e613d6c-06d0-47e4-ade0-872575402302",
    "code": "volume",
    "properties": {
      "volume": 1
    }
  }
}
 ```
5. The registered unit is `0.6466477675381944 units` instead of `1`.

**Expected behavior**
The registered unit is should be `1`

**Screenshots**
1. Volume billable metric
<img width="733" alt="Screenshot 2024-04-11 at 7 49 12 PM" src="https://github.com/getlago/lago/assets/40957514/20ee4710-7f38-42ed-a307-309ebde8bda7">

2. Plan settings
<img width="726" alt="Screenshot 2024-04-11 at 7 53 34 PM" src="https://github.com/getlago/lago/assets/40957514/a5d872f0-c136-49fb-b8ec-3091259454a5">

3. Usage before triggering the event shown above.
<img width="848" alt="Screenshot 2024-04-11 at 7 54 30 PM" src="https://github.com/getlago/lago/assets/40957514/95362d74-bcb0-4581-8b17-4e8fd78885b3">

4. Usage after triggering event shown above.
<img width="848" alt="Screenshot 2024-04-11 at 7 55 09 PM" src="https://github.com/getlago/lago/assets/40957514/2b294a61-5985-442a-99d5-16db6cf5f883">

**Support**

**Additional context**

**Comment by mathieu-lago** [comment]
Hi @AyushChothe - as described in the documentation, `weighted_sum_agg` automatically prorates usage to the second, based on the timestamp of your event. Therefore, you can only see a full unit when the timestamp of your event corresponds to the first second of the billing period.

https://docs.getlago.com/guide/billable-metrics/aggregation-types/weighted-sum
