### ISSUE TITLE
Create a smooth connection between Lago <> Salesforce

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#34]
## Problem description
Custom plans can be created in Salesforce by Sales directly with their customer. By creating them, it's not linked to Lago.

_How important is this for you?_

**Comment by mtews** [comment]
We'd prefer an integration with HubSpot ;-) Actually, I think enabling sales people to create custom plans is an important feature especially for B2B companies, as we practically do this for 50% of our customers.

**Comment by bert-air** [comment]
+1 for hubspot intégration !

**Comment by ttrushin** [comment]
An integration to Salesforce would be huge!

**Comment by michaelponrajah** [comment]
### We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Create a smooth connection between Lago <> Salesforce - Canny](https://getlago.canny.io/feature-requests/p/integration-with-salesforce)
