### ISSUE TITLE
Create a charge model applying a percentage (% + fixed rate)

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#35]
## Problem description
1. Company using Lago cannot charge a percentage on a usage-based feature
2. It's useful for companies taking a cut out of an amount or a revenue (charity, fintech companies)

_How important is this for you?_

**Comment by michaelponrajah** [comment]
## `Create a charge model applying a percentage (% + fixed rate)` is now live in production 🎉

### Useful links
[Documentation](https://doc.getlago.com/docs/guide/plans/charges#the-percentage-charge-model)
[Changelog](https://doc.getlago.com/changelog/percentage-charge-model)
