### ISSUE TITLE
[Feature]: Missing Elixir / Erlang Client 

### ISSUE THREAD

**Issue by packetlost** [getlago/lago#353]
We are the redheaded stepchildren... I know... I know.

But Elixir needs that Lago magic too. We need to meter functions too. :D

Sure, we could use JS, but there are advantages to writing pure elixir code.

Ruby gets that sweet sweet love. Rust too, loved well. But, Elixir.... forlorn!

**Comment by vincent-pochet** [comment]
Thank you for these nice words @packetlost :smile: 

Sadly, at the moment, we do not have the workforce and the knowledge on our side to work on an Elixir/Erlang client. So we cannot give you visibility on this topic.

Lago is open to external contribution so feel free to create one if you want.
[Lago OpenAPI definition](https://github.com/getlago/lago-openapi) can be used as a source.
