### ISSUE TITLE
[BUG]: Development Environment Setup not working

### ISSUE THREAD

**Issue by AyushChothe** [getlago/lago#365]
**Describe the bug**

I followed the https://github.com/getlago/lago/wiki/Development-Environment guide.
The API doesn't respond, so I cannot log in or sign up. Also, the `license` image is not present in the `docker-compose.dev.yml`

<img width="1510" alt="Screenshot 2024-06-23 at 8 46 22 PM" src="https://github.com/getlago/lago/assets/40957514/108fb8aa-b8cb-4334-9d2d-bc38c209da74">

**Comment by AyushChothe** [comment]
@jdenquin Please help me resolve this. I want to add a Payment Provider that will help Indian companies use Lago seamlessly.

**Comment by AyushChothe** [comment]
**Update**: It's working now. Removed `traefik` from `docker-compose.dev.yml` opened appropriate ports and changed environment variables accordingly.

**Comment by jdenquin** [comment]
@AyushChothe we all run the dev environment with `traefik` without any issue.
Your error `ApolloError` is because the front end can't join the back end.

All good if you find a way to make it works!
