### ISSUE TITLE
[BUG]: Initializing a clean database on 1.6 fails

### ISSUE THREAD

**Issue by Citrullin** [getlago/lago#369]
**Describe the bug**
When cloning the repository and setting up the docker container the postgres setup will fail.

**To Reproduce**

1. Inspect the existing used postgres database with `docker inspect [HASH]`
2. Note down all used volumes under `Mounts`. Especially their `Name` and `Source` .
3. Backup all noted down directories. (We need a clean setup)
3. Stop the lago container with `docker stop [HASH]` or all container with `docker stop $(docker ps -a -q)`. 
   `docker compose down` should also do the job.
4. Remove the container with `docker rm [HASH]` or all container with `docker rm $(docker ps -a -q)`
    Skip when using `docker compose down`. It should remove the container.
6. Remove the noted volumes with `docker volume rm [NAME]`

**Expected behavior**
A successful database setup.

**Actual behavior**
When checking the postgres container with `docker logs [HASH]`
```bash
2024-07-02 02:38:15.735 UTC [88] ERROR:  relation "invoices" does not exist at character 523
2024-07-02 02:38:15.735 UTC [88] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
               pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
               c.collname, col_description(a.attrelid, a.attnum) AS comment,
               attidentity AS identity,
               attgenerated as attgenerated
          FROM pg_attribute a
          LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
          LEFT JOIN pg_type t ON a.atttypid = t.oid
          LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
         WHERE a.attrelid = '"invoices"'::regclass
           AND a.attnum > 0 AND NOT a.attisdropped
         ORDER BY a.attnum

2024-07-02 02:38:15.782 UTC [89] ERROR:  relation "subscriptions" does not exist at character 523
2024-07-02 02:38:15.782 UTC [89] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
               pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
               c.collname, col_description(a.attrelid, a.attnum) AS comment,
               attidentity AS identity,
               attgenerated as attgenerated
          FROM pg_attribute a
          LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
          LEFT JOIN pg_type t ON a.atttypid = t.oid
          LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
         WHERE a.attrelid = '"subscriptions"'::regclass
           AND a.attnum > 0 AND NOT a.attisdropped
         ORDER BY a.attnum
```

**Workaround**
1. Change the version of all lago images in `docker-compose.yml` from `1.6` to `1.5`
2. `docker compose up -d` (Ignore the pdf error)
3. Check the logs of the postgres database with `docker logs [HASH]`. The last message should look like this:
```bash
2024-07-02 02:43:01.834 UTC [27] LOG:  database system was shut down at 2024-07-02 02:41:11 UTC
2024-07-02 02:43:01.843 UTC [1] LOG:  database system is ready to accept connections
```
4. Shutdown and remove the container with `docker compose down`
5. Change the version in the `docker-compose.yml` from `1.5` to `1.6`
7. Run `docker compose up -d`
8. Open the frontend, log in and check the logs of the postgres container with `docker logs [HASH]`.
   It should run without any issues.

**Additional context**
It's important to have a fresh setup. A migration from 1.5 -> 1.6 will be successful.

**Comment by vincent-pochet** [comment]
Thank you @Citrullin  for reporting this  

This happen because the application is started with `docker compose up -d` that is starting all containers, including the `clock` container.
This last one could start automatically some background task before the execution of all database migrations that are started by the `api` container, leading to some error due to missing tables/columns.
This is not critical as the clock will perform the task later, and since it's a fresh install, nothing is really waiting for processing.

This situation is not specific to 1.6, it could happen with any other version.

The proper workaround is to start the clock container only after everything is up and running:
- Start api and worker containers
```bash
docker-compose up -d api api-worker
```
- Wait for all migrations to be executed
```bash
docker compose exec api rails db:migrate:status
``` 
- Start the front and the clock
```bash
docker-compose up -d front api-clock
```

I will update the documentation with these steps to help future users.
