### ISSUE TITLE
[BUG]: 宿主机上已经占用了3000端口，即使在lago的docke-compose.yml中修改了3000端口为其它未占用端口，但docker运行后，仍然是监听3000端口，导致lago不能正常访问

### ISSUE THREAD

**Issue by hezuogongying** [getlago/lago#380]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Support**

**Additional context**

**Comment by jdenquin** [comment]
can you edit and write your issue in english? 🙏

**Comment by jdenquin** [comment]
Closing since the description is not provided.
