### ISSUE TITLE
[BUG]: Date confusion in invoices written in French

### ISSUE THREAD

**Issue by qvignaud** [getlago/lago#386]
**Describe the bug**
In generated PDFs invoices, date is abbreviated on three letters and if makes confusion in French for June (Juin) and July (Juillet) months: both becomes `Jui`.

**To Reproduce**
Generate any invoice in French during June or July.

**Expected behavior**
Avoid date confusion, either by abbreviating to commonly used `Juin` and `Juil.`, or just don't make any abbreviation on dates by always using full name of months (as other languages may have same issue) or numeric format (but then other localization issues may happen).

**Screenshots**
![Capture d’écran du 2024-07-25 12-12-04](https://github.com/user-attachments/assets/d6d6ed57-46c5-4a69-8607-c5424ce14dc6)

**Additional context**

**Comment by rsempe** [comment]
Thanks @qvignaud 👍
