### ISSUE TITLE
[BUG]:  Incorrect parameter `void_credits` in API documentation should be `voided_credits`

### ISSUE THREAD

**Issue by kkeval** [getlago/lago#394]
#### Description:
There is an issue in the [Lago API documentation](https://getlago.com/docs/guide/wallet-and-prepaid-credits/wallet-top-up-and-void) where the parameter `void_credits` is incorrectly used. The correct parameter should be `voided_credits`.

#### Steps to Reproduce:

1. Use the following cURL request from the documentation:
    ```bash
    curl --location --request POST "$LAGO_URL/api/v1/wallet_transactions" \
      --header "Authorization: Bearer $API_KEY" \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "wallet_transaction": {
          "wallet_id": "wallet_1234567890",
          "void_credits": "20.0",
          "metadata": [
            {
              "key": "top-up-type",
              "value" "manual-void"
            }
          ]
        }
      }'
    ```
2. Execute the cURL request.

#### Observed Behavior:
The response contains an empty `wallet_transactions` array:
```json
{
    "wallet_transactions": []
}
```

#### Expected Behavior:
The request should successfully process the `wallet_transaction` with the provided credits. However, this only works if the parameter `voided_credits` is used instead of `void_credits`.

#### Corrected API Request:
```bash
curl --location --request POST "$LAGO_URL/api/v1/wallet_transactions" \
  --header "Authorization: Bearer $API_KEY" \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "wallet_transaction": {
      "wallet_id": "wallet_1234567890",
      "voided_credits": "20.0",
      "metadata": [
        {
          "key": "top-up-type",
          "value" "manual-void"
        }
      ]
    }
  }'
```

With the corrected parameter, the response is as expected.

#### Additional Information:
- **Lago Version:** 1.9.0
- **Operating System:** Ubuntu 22.0
- **VM Details:** N/A
- **Packages Installed:** N/A

Please update the documentation to reflect the correct parameter name.

**Comment by kkeval** [comment]
I have fixed the issue in the doc repo here's is the PR -  [DOC PR](https://github.com/getlago/lago-doc/pull/187), i forgot to raise the issue in the docs repo

**Comment by mathieu-lago** [comment]
Hi @kkeval - thanks for the heads-up and your PR. I've approved it and it has been merged.
