### ISSUE TITLE
Event filtering on aggregation types for usage-based billing

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#40]
## Problem description

When receiving events, a user is not able to filter it with an existing property.
For example, you receive a billable event anytime there is a new transaction, but you want to filter by transaction having a `completed` status. You don't want to implement the logic on your backend and that's totally fine

We should be able to filter events coming in Lago and bill only filtered events

_How important is this for you?_

**Comment by michaelponrajah** [comment]
We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Event filtering on aggregation types for usage-based billing - Canny](https://getlago.canny.io/feature-requests/p/event-filtering-on-aggregation-types-for-usage-based-billing)
