### ISSUE TITLE
[BUG]: Bahrain Dinars Currency is missing.

### ISSUE THREAD

**Issue by juandl** [getlago/lago#422]
**Describe the bug**
Based on this doc https://getlago.com/docs/api-reference/resources/currencies#currencies, there's a currency missing "Bahrain Dinars" 

**To Reproduce**

**Expected behavior**
It should contain all the currencies around the world

**Screenshots**

**Support**

**Additional context**

**Comment by jdenquin** [comment]
https://github.com/getlago/lago-api/pull/2758 Added!

Will be available on the next release

**Comment by juandl** [comment]
@jdenquin Kuwait Currency is missing too :sweat_smile: , which is KWD

**Comment by juandl** [comment]
https://github.com/getlago/lago/issues/425
