### ISSUE TITLE
[FEAT]: Ability to disable signup

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago#47]
For those of us who are self-hosting, allowing signup after the initial organization(s) are created doesn't make sense.

One solution would be to set an environment variable, e.g. `LAGO_SIGNUP_DISABLED` which would remove the ability to signup on both the front-end and graphql. Or maybe there's already some feature flagging system that could be used instead.

We are willing to do the work if a PR would be accepted.

**Comment by vincent-pochet** [comment]
Hello @prognostikos,

Thank you for the suggestion and contribution proposal.

Indeed it makes perfect sense in a self-hosting scenario. For now, we do not have such feature flag.

As you are suggesting, a flag stored in an environment variable could perfectly do the job.
It's not on our roadmap for now, but we would be happy to review and merge a PR if you want to work on it on your side.

Cheers

**Comment by prognostikos** [comment]
@vincent-pochet @jdenquin I will add this today, but would like a confirmation that I'm doing it the right way as I've not used GraphQL before.

From what I can see adding a `.visible?` class method in the `Mutations::RegisterUser` mutation would be the way to block this feature from use depending on the ENV var. 

Do I  also need make a change on the front-end to hide the `sign up` link? Or will this automatically be done if the mutation is not visible?

**Comment by ansmonjol** [comment]
Hey @prognostikos,

Thanks a lot for your proposal.

I'll handle the front-end side and 
- hide the signup link
- prevent accessing the signup page via URL
when `LAGO_DISABLE_SIGNUP` env variable will be present.

I've discussed with @vincent-pochet and he told me the change you performed on your branch should do the job perfectly 🙌 

I'll let you know when I'm done on my side.

Thanks again, also for your patience ;)

Have a nice weekend,
Alex

**Comment by ansmonjol** [comment]
@prognostikos I've open a MR on the frontend app https://github.com/getlago/lago-front/pull/236
Once merged you will be able to test your changes using the last front version on main branch.

**Comment by vincent-pochet** [comment]
This feature will be part of the next  0.5.0-alpha release
