### ISSUE TITLE
[FEAT]: add Event show API endpoint

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago#48]
We want to be 100% sure that our events have been created as our revenue depends on it. The current system optimizes for throughput by enqueuing a Sidekick job in Redis to create the event. Depending on the Redis configuration, [there is a possibility of losing data if Redis crashes before the job can be worked](https://redis.io/docs/manual/persistence/#how-durable-is-the-append-only-file). And unfortunately many cloud providers limit what configuration options are available.

We would love to have a confirmation that the event is safely stored in Postgres. One way to achieve this would be to send our webhook endpoint an `event.created` webhook with the event that has been created. Then we can update our system to mark the outgoing billing event as "created_in_billing_system" or whatever.

We are willing to submit a PR if this is something Lago wants to support.

**Comment by vincent-pochet** [comment]
Hey @prognostikos,

We recently introduced two features to improve confidence in event ingestion:
- The [event debugger](https://doc.getlago.com/docs/guide/events/debugger)
- `event.error` webhook for failed events: https://github.com/getlago/lago-api/pull/252

But we are aware that it does not guaranty that all events will be processed in case of Redis outage or misconfiguration.

Having a webhook for `event.created` would certainly fix the problem but at the cost of many webhooks sent back to the source.
So it would also probably require a way to be able to chose which webhooks an application wants to receive before enabling it.

We also discussed about adding an API endpoint to download the logs of all received events. It would allow an easy reconciliation between an app and Lago. Would it be an acceptable option for you?

For now, we do not have action on our short term roadmap to tackle this but we are marking it as a feature request.
Also we would be happy to discuss about how it could be implemented.

Cheers

**Comment by prognostikos** [comment]
Thanks @vincent-pochet the debugger looks useful.

I understand that not everyone would want to get the event.created webhook and right now it's not possible to configure which events are sent to a webhook endpoint nor to have multiple endpoints.

For us an API endpoint where we can GET on say `transaction_id` would work. We would probably just setup a job in our system to confirm each ingested event in 60 seconds or something like that.

Getting logs of all received events would also be useful, but may require a bit more work on the caller end.

We will need some way to confirm event creation, so we are happy to do the work on the API and ruby client for this. Adding an endpoint to GET an event by transaction_id seems pretty straightforward. If you'd prefer an endpoint to download logs maybe you could start by describing what parameters it should take and what the response should look like and we can take it from there?

**Comment by vincent-pochet** [comment]
Thanks @prognostikos for your contribution proposal.

I agree that a `GET /api/v1/events/:transaction_id` looks like a simple solution for your need.
Let me discuss it with the product and tech teams and I will get back to you today.

**Comment by vincent-pochet** [comment]
After discussing internally, we think that adding a new API route is the easiest way to move forward with it for now.

We will probably improve the webhook side in the future, but not in the short term.

If you want to take care of this dev, we would be pleased to review and merge it in the main branch for future release :rocket:
