### ISSUE TITLE
[FEAT]: OAuth2 authorization 

### ISSUE THREAD

**Issue by maciejstromich** [getlago/lago#49]
**Is your feature request related to a problem? Please describe.**
Many of the organizations already have a IdP available. Lago could leverage e.g. OAUTH2 (as it's currently one of the most popular protocols) to give ability to authorize API requests and give ability to login via the frontend which could potentially be beneficial in case of other features like giving access to usage/invoicing data that is currently being developed.

**Describe the solution you'd like**
use one of the sso libraries avialable and give ability to configure required paramters. Give ability to restrict who can use the system based at least on some group or give ability to configure the permission field from the JWT.

**Comment by sarkissianraffi** [comment]
Hi @maciejstromich, very clear description thanks.
We are currently assessing this feature during our tech daily. We'll come back to you soon.
Thaks

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/oauth2-authorization
