### ISSUE TITLE
[FEAT]: Allow creating an invoice out of cycle

### ISSUE THREAD

**Issue by jerbob92** [getlago/lago#51]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be nice to force creating an invoice before the billing cycle end, for example to immediately create an invoice for a one-off add-on that has been added.

**Comment by sarkissianraffi** [comment]
Hi @jerbob92, 
We have already this feature, at least it's a feature really close to what you are describing. It's related to this [issue](https://github.com/getlago/lago/issues/23). 

We called this feature **add-ons**: it allows you to create a one-off fee that is invoice straight away.

- Documentation guide: https://doc.getlago.com/docs/guide/addons
- API Ref: https://doc.getlago.com/docs/api/applied_add_ons/applied-add-on-object

I can also share this [webhook documentation for add-ons invoicing ](https://doc.getlago.com/docs/api/webhooks#add-on-applied-to-customer).

If you need something a bit different, we can jump on a call anytime!

**Comment by jerbob92** [comment]
Hi @sarkissianraffi 

I think my description maybe wasn't clear enough. I know about the add-ons (I also refer to them in the description). 
I'm talking about actually generating the invoice itself out of the billing cycle. So a button that says "Create Invoice now" that would get all the usage + add-ons that are unbilled to that point and then generate the invoice.

**Comment by sarkissianraffi** [comment]
Got you! Let's dig into it as this has impact on the way charges are distributed into invoices (for instance, what happens to usage happening after the invoice finalized in advance?).
Reaching out to dig deeper into your requests (probably gathering chats with Mathieu); Thanks!

**Comment by sarkissianraffi** [comment]
Hi @jerbob92, based on the discussion we had, we investigated on the bug for add-ons invoicing. It seems to work well on our side for all environments. Here is a [Loom link](https://www.loom.com/share/e5a7b3e383914642955701024196c073) showing you how I managed to test it. Can you do the same tests so we can unblock you?
Thanks a lot!

**Comment by jerbob92** [comment]
Hi @sarkissianraffi 
Just tested it again, I can confirm that the invoice appears after a refresh!

**Comment by sarkissianraffi** [comment]
Hi @jerbob92, great! We'll work on improving this invoice's display. If any issues on the frontend side, you can use the webhook to catch invoice created, both for subscriptions & add-ons. In the meantime, we work actively on the other feature requests (as they were already plan for this dev cycle). We will reach out when everything is ready to be deployed!
Thanks
