### ISSUE TITLE
[FEAT]: Allow doing an invoice dry-run

### ISSUE THREAD

**Issue by jerbob92** [getlago/lago#52]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to create a dry-run invoice to test what kind of invoice would be created when an invoice would be created at date *x*

**Comment by derekperkins** [comment]
This would be very helpful

**Comment by joaolcorreia** [comment]
I would add a preview of the invoices that will run for the next x 30 days (even if billable events are current with a red background at the current values).

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/invoice-dry-run
