### ISSUE TITLE
Overwrite plan and charges for a specific customer

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#57]
## Problem description
Some users requested the possibility to overwrite a plan & charges amount for a specific customer, without having to recreate a new subscription.

**Comment by michaelponrajah** [comment]
## `Overwrite plan and charges for a specific customer` is now live in production 🎉
When assigning a plan to a customer, you can now duplicate an existing plan and create a new one based on the parent one.

### Useful links
[Changelog](https://doc.getlago.com/changelog/overwrite-plans)
