### ISSUE TITLE
Supporting custom interval for billing period (days, weeks, quarters or semesters)

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#58]
## Problem description
Lago offers for now 3 types of billing period. Monthly, yearly and weekly. But some users have a more granular need, like daily or quarterly.

**Comment by jpattWPC** [comment]
Would like to pile onto this issue, We bill every 4 weeks for some clients, others we bill monthly or on other schedules.

**Comment by jiadar** [comment]
Yes, we have a client wanting to bill every 28 days. This allows them capture an "extra" payment each year.

**Comment by michaelponrajah** [comment]
### We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Quarterly interval - Canny](https://getlago.canny.io/feature-requests/p/quarterly-billing-interval)

Don't hesitate to share your ideal interval in the Canny discussion
