### ISSUE TITLE
Open API endpoints to use Lago either with the API only or in whitelabel

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#60]
##Problem description
Creating a plan or a billable metric is doable from the UI. But some users want to use the API only to use the full billing solution offered by Lago

**Comment by prognostikos** [comment]
This is something we've considered adding as well, as we have 80+ plans to add with several billable metrics for each at different price points

**Comment by sarkissianraffi** [comment]
Hi @prognostikos! This feature is currently in progress, probably released end of next week. You will be able to create billable metrics directly from the api. Keep in touch 🚀

**Comment by sarkissianraffi** [comment]
This feature has been release => https://doc.getlago.com/changelog/new-api-endpoints
