### ISSUE TITLE
[FEAT]: Support billing in customer timezones

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago#61]
From what I can tell Lago currently selects events to be used to calculate fees, etc. by selecting all fees in a given month/year/(etc) time range. However, the time zone used for that select seems to be the system timezone, which will default to UTC in Rails unless configured otherwise.

We have customers in different timezones, and we currently bill customers for usage in their timezone. So a UK customer and a DK customer will include fees for events in two different time ranges, even though they are both for say "usage in June".

Is this something Lago would like to support? If so we would be happy to contribute a PR.

**Comment by vincent-pochet** [comment]
Hello @prognostikos, 
Thank you for your raising this point.

Indeed for now Lago is handling events using the timestamp field which is supposed to be an UTC value.

A proper way to address your issue would be to store a `timestamp_in_customer_timezone` along with the actual timestamp and to adapt the billing and aggregation logic to use this field.
This change is not in our short term roadmap, but we are taking it into account for future iteration as you are certainly not the only user with this concern.

In the meantime, a workaround for you could be to add the timezone difference in the `timestamp` field sent in the event payload. Do you think this could do the job for now?

**Comment by prognostikos** [comment]
@vincent-pochet making sure the timestamp is always a UTC value partially works.

Isn't it the case that if fees are always calculated early in the first day of the month UTC it will exclude events that from the customers point of view should be included if the customer timezone has a negative UTC offset? I think Lago will have already calculated the fee for that month even if more events come in on the same day for the customer's timezone. And it would be the same for events at the beginning of the month if the customer timezone has a positive UTC offset.

To support this feature I think that Lago would have to try to bill every hour for subscriptions / customers where the billing period in their timezone starts in that hour.

**Comment by prognostikos** [comment]
Another option would be to make the day of the month where the fees are calculated configurable so that there is a long enough delay between event receipt and fee calculation - today we actually bill on the 4th for activities in the previous month. We are planning to reduce that but it wouldn't be a problem to wait 1 day or however many hours it would take to cover all customers.

**Comment by vincent-pochet** [comment]
@prognostikos Sorry for the late answer on this topic.
Indeed, I think the easiest way to support this for now would be to change the default billing day or to make it editable. We are discussing it internally and we will come up with a solution soon.

Thank you for your patience.
