### ISSUE TITLE
[FEAT]: Reverse a charge

### ISSUE THREAD

**Issue by hampsterx** [getlago/lago#67]
Our Scenario: Customers get charged a commission (billable unit) but very ocassionally we want to revert that charge when the transaction is cancelled.

We thus need to be able to either send the same event again but have Lago know to revert the charge or an API endpoint perhaps?

The complexity also is that these customers are on a Graduated charge model. Thus if there are charges after that one to revert that were charged into the next tier, in a perfect world they would be recalculated but that seems highly problematic to implement.

**Comment by sarkissianraffi** [comment]
Hi @hampsterx, that's a good feature request, thanks a lot!
What if the event reverted belong to a former billing period (and has already been invoiced)? We just ignore it? (ie: the event, to be reverted, has to be in the current period?). When the charge is running under the current period, we could be able to recalculate everything when an event is reverted, regardless the price model (graduated, package etc...).

This answer could help us scope the feature. Thanks again! 👍

**Comment by hampsterx** [comment]
hi @sarkissianraffi , well that was another question I had. What happens when you back populate events (previous billing periods)? In our case we have graduated tier that are multiple year but regardless for the current year they are partway through so we need to ensure when we migrate to Lago that they are at the correct usage going forward. Pretty sure this is fine though just the invoice will only be raised if in the current month? Anyhoo..

In our use case I think it's perfectly fine to expect the reversal to be in the current billing month and ignore it if not.

> we could be able to recalculate everything when an event is reverted, regardless the price model

Well that is really the best possible scenario, assuming the reversals are very infrequent (which they are in our case).

> Some events can be ingested but triggering a bad or unexpected behavior. 

Adding a warning if its not in current month would be helpful. I think in general anything being "ignored" should at least generate a warning so the behaviour is transparent and actionable if required.

**Comment by sashahilton00** [comment]
Wanted to voice my support for some version of this feature as well. The scenario in which we would be using Lago is one of where the platform in question is acting as a form of broker. This means that a customer is billed on a per event basis upfront (eg. `contract.created`), but in the event of the contract not completing, the contract is refunded (`contract.refunded`). 

With regards to how this might work, in #105 the importance of the event audit trail is highlighted, and above the need to account for possible different billing periods. Would it be possible to add some form of event, eg.  an _adjustment event_, where such an event requires a previously submitted metered event transaction ID, and accepts an `operation_type` (such as in the persisted event), with possible options of `add`, `subtract`, `multiply` or `void`, where the first 2 accept the usual `key`: `value` properties to modify the original event accordingly, without overwriting the original event?

For the purposes of aggregation, the operation_type can be used to infer what changes should be made to the original event values during aggregation calculations.

The other option I have yet to experiment with is negative values in events, which may provide an alternative means to adjusting prior metered events without overwriting them, though this will require extra work by the client to retrieve the original event and calculate the adjustment amount.

**Comment by mathieu-lago** [comment]
Fees related to instant charges can be refunded. It is also possible to issue credit notes for other types of fees.

https://doc.getlago.com/docs/api/fees/update-fee
https://doc.getlago.com/docs/guide/credit_notes
