### ISSUE TITLE
Native connection with a Direct Debit PSP (Gocardless)

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#69]
## Problem description

A native connection has been created between Lago & Stripe. This is useful to get paid with credit cards or wires when a Lago invoice is emitted. However, it's not possible to use a Direct Debit payment provider. It could be very useful for our users if they want to get paid with direct debits, directly on their customers' accounts.

**Comment by Bredo** [comment]
Stripe does actually offer both [SEPA DD (EU)](https://stripe.com/docs/payments/sepa-debit), and [BACS DD (UK)](https://stripe.com/en-gb-dk/payments/bacs-debit) natively, as well as Bank Debits in [ACH (US), Pre-auth Debit (CA), and BECS (AU)](https://stripe.com/docs/payments/bank-debits).

But from your perspective, GoCardless will probably offer you nice revenue share for embedding them? They do however charge quite larger fees than Stripe to the merchants.
