### ISSUE TITLE
Incremental & Decremental Events (keep persistency on recurring billing metric)

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#77]
## Problem description
For now, you need to send events for each period, including when the metric to be charged is recurring period over period. Let's take the example of `credit cards`, `user seats`, or `integration connected`. They are consumed once, but they are also persistent period over period, unless an unusual event deprecates it.
Lago should be able to keep this persistent metric in memory so they are recurring period over period, unless you decrement it.

**Comment by michaelponrajah** [comment]
## `Incremental & Decremental Events` is now live in production 🎉

### Useful links
[Documentation](https://doc.getlago.com/docs/guide/billable-metrics/aggregation-types#persistent-aggregation-types)
[Changelog](https://doc.getlago.com/changelog/recurring-count)

**Comment by linbuxiao** [comment]
> ## `Incremental & Decremental Events` is now live in production 🎉
> ### Useful links
> [Documentation](https://doc.getlago.com/docs/guide/billable-metrics/aggregation-types#persistent-aggregation-types) [Changelog](https://doc.getlago.com/changelog/recurring-count)

where is the feature?

**Comment by julienbourdeau** [comment]
The feature is "recurring charge": https://docs.getlago.com/guide/plans/charges/metered-vs-recurring
