### ISSUE TITLE
Prices Caps and Prices Minimums

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#78]
## Problem description
Subscriptions and charges are billed with a defined price model (standard, package, graduated, percentage). However, over-consumption does not mean that your customers have an unpredictable pricing. Lago should handle a full logic of price minimums and price caps. No surprise for you, no surprise for your customer.

**Comment by derekperkins** [comment]
This is important for us

**Comment by Bredo** [comment]
If this is coupled with outgoing webhooks, i.e. to limit an account at a customer-specific threshold, it would be very powerful! Perhaps this could be an amount in the subscription currency, or a number of events?

**Comment by michaelponrajah** [comment]
### We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Prices Minimum - Canny](https://getlago.canny.io/feature-requests/p/minimum-contract-value)
