### ISSUE TITLE
Create % discount coupons and recurring coupons

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#79]
## Problem description

For now, Lago does not support 
- coupons in % (percentage of a price that needs to be deducted for a period of time)
- recurring coupons period over period till expiry date is hit
- coupons applied to a specific subscription or plan

Let's improve this!

**Comment by michaelponrajah** [comment]
## `Create % discount coupons and recurring coupons` is now live in production 🎉
Coupons got a new method, you can now apply a percentage coupon on invoices.
Coupons can now have a recurrence on the customer.

### Useful links
[Documentation](https://doc.getlago.com/docs/guide/coupons#create-coupons)
[Changelog](https://doc.getlago.com/changelog/coupons-v2)
