### ISSUE TITLE
Display a custom charge name in an invoice

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#80]
## Problem description

A billable metric can be reused in several charges. However, the same name will be displayed in the invoice, which is confusing. Lago should allow to display a custom charge name in invoices

**Comment by michaelponrajah** [comment]
We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Custom charge name - Canny](https://getlago.canny.io/feature-requests/p/add-a-custom-charge-unit-name)
