### ISSUE TITLE
Unable to Install my own SSL Certificate in "lago-api" Docker Container.

### ISSUE THREAD

**Issue by stsajid** [getlago/lago#82]
Hi,
I have deployed lago through Docker on my AWS EC2 Instance. 
Now the problem is if I set my LAGO_FRONT_URL and LAGO_API_URL to my instance's public IPv4,  I can succesfully login but cannot copy the api from the Copy API button. getting the error <b>"Cannot read properties of undefined (reading 'writeText')"<b>

So I looked into this error and found that my frontend and api should be on "HTTPS" or either the button will not work.

So I installed my own certificate in <b>"lago-front"</b> Docker container through nginx but I am unable to install the ssl cerificate on the api container. Since 443 port of my instance is already bound to lago-front container I cannot bind it to lago-api container.

I also found another way to install certificate which was installing it directly through rails i-e <b> rails s puma -b 'ssl://0.0.0.0:9292?key=path_to_key.key&cert=path_to_cert.crt&verify_mode=none&ca=path_to_root_bundle.crt' <b>

When I try to install the certificate through puma it says addressport 3000 is already in use. 
Obiously because the api is running on 3000 port it wont start the server on the same port. 

I am stuck here. Kindly help me with the installation of SSL certificate on the api docker container.
I did this setup on my personal machine and it was running perfect because the url was localhost but on the ec2 instance I am facing this ssl issue.
Need to install my own SSL certificate, not from letsencrypt.

**Comment by michaelponrajah** [comment]
Hey @stsajid, let me check with an engineer and get back to you asap!
cc. @jdenquin

**Comment by jdenquin** [comment]
Hello @stsajid,

It should be better for you to use a proxy in front of the API and the Front end so you can easily use your own SSL certificate.
You can take a look at `traefik` like we do on our development environment, it's pretty easy to setup, or you can use an AWS ELB in front of your EC2.

Do not hesitate to join our [Slack](https://lago-community.slack.com/ssb/redirect) then we can discuss about it directly!

**Comment by jdenquin** [comment]
@stsajid any update on this? 🙏

**Comment by stsajid** [comment]
> @stsajid any update on this? 

Yes I have resolved this issue by re-dockerizing the lago-api image. I dockerized the api code on an Apache-Ubuntu Image. and Installed the certificate their. 
Created a virtual host in the new dockerized lago-api docker container with a different port. 
I installed the certificated directly through ruby i-e
 ( <b> puma -b 'ssl://0.0.0.0:3000?key=path_to_key.key&cert=path_to_cert.crt&verify_mode=none&ca=path_to_root_bundle.crt' <b> )

**Comment by stsajid** [comment]
There's one more issue I cannot open Customers or access Customers Details. Every other modules and options are working fine but when I add a customer it creates it but also throws error of <b> POST "https://myurl:3000/graphql"  Internal Server 500 Error </b> . When I click on the created customer I get the same error in console. It tell to refresh the Customers page but keeps getting the same error.
