### ISSUE TITLE
[FEAT]: create a smooth connection to Mollie payment provider

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago#84]
just as you have a great integration with stripe, a nice integration with Mollie https://www.mollie.com  would be amazing!

n.b. they already have an active ruby-client https://github.com/mollie/mollie-api-ruby

**Comment by sarkissianraffi** [comment]
Hi @c-nv-s, very clear thanks! The plan is to add more and more native integrations, including PSPs like Mollie. We'll try to make it fit within the roadmap and will tell you whenever it's prioritize. If you want to have closer contacts with the team, please join https://getlago.com/slack (if your not in already). Thanks!

**Comment by c-nv-s** [comment]
Thanks I'll keep an eye out.
Mainly using Discord not Slack but thanks anyway

**Comment by smashah** [comment]
+1 for mollie. +2 for discord - I'm interested in long term being part of the lago community but don't want to keep memory-hog slack opened just for lago. Please consider migrating community to discord @sarkissianraffi thanks

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/support-integration-with-mollie-as-payment-provider
