### ISSUE TITLE
[BUG]: copy api key to clipboard error

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago#87]
**Describe the bug**
click to copy api key functionality does not work on firefox 91

error message in console:
Uncaught (in promise) TypeError: navigator.clipboard is undefined

**To Reproduce**
Menu > developers > apikeys
click on copy button and observe console in browser developer tools

**Expected behavior**
API key is copied to system clipboard

**Screenshots**

**Support**
 - Browser firefox 
 - Version 91

**Additional context**
lago version 0.4.0-alpha

**Comment by ansmonjol** [comment]
Hello @c-nv-s,

Thanks a lot for reporting this issue 🙂

In order to make sure you're not experiencing an issue related to your environment, can you try to update your browser to the latest version please ?

If the issue persists, can you tell us if you're in development mode in local or using a different environment ?

If you want to have a direct chat with us, feel free to join our [Slack community here](https://join.slack.com/t/lago-community/shared_invite/zt-1dwisaspe-M_WW8bEPlqVh~PiD6bjQ0Q)

**Comment by c-nv-s** [comment]
I am on the latest firefox version for the default OS and using private browsing.
regarding dev mode or different environment: I am running straight from the docker-compose.yml file inside a virtual machine with only the domain changed from "localhost" to a custom local domain and changed the exposed port from 80, 443 to  8080, 8443.
I am running 0.4.0-alpha (because 0.5.0 lago-api doesn't run and shows error in the docker log)
If you are not able to reproduce the issue then perhaps it is just my environment, eventually I'll look to set up a more "production-like" setup and see if the issue still exists.

**Comment by ansmonjol** [comment]
Thanks for all the details! Very helpful.

Our best guess is that you may have "removed" the secure navigation (https) with the port forwarding somehow. Could that be the case? Clipboard API seems to be strictly limited to work only on localhost or over secure connection. See https://web.dev/async-clipboard/#security-and-permissions

As a side note, `lago-api v0.5.0` indeed has an issue and a fix will be deployed today.

Please let us know if you were able to move forward on this.

**Comment by c-nv-s** [comment]
OK thanks for the info on the clipboard api, that is likely the issue so I will close this ticket and only report again if it still exists after setting up lago over https

**Comment by ansmonjol** [comment]
BTW a [new version](https://github.com/getlago/lago-api/releases/tag/v0.5.1-alpha) of API have just been merged. It should fix the error you faced
