### ISSUE TITLE
POST Internal Server 500 Error on Adding Customer or viewing Customer

### ISSUE THREAD

**Issue by stsajid** [getlago/lago#88]
I have installed my own certficate in lago-api container through <b> puma -b 'ssl://0.0.0.0:3000?key=path_to_key.key&cert=path_to_cert.crt&verify_mode=none&ca=path_to_root_bundle.crt'</b>

Everything is working fine but when I Add Customers or view them I get POST (https://[my-Lago-api-URL]:3000/graphql) 500 Internal Server Error.

Although the api seems to be working fine because every other functionality is working like creating Coupons Plans Metrics etc.. 

I am getting this error when I add Customers. The customer gets added but the error is their and when I view the created customers I get the same error and Lago tells me to refresh the Customers page. Nothing happens when I refresh it. Gets the same error.

**Comment by vincent-pochet** [comment]
Hello @stsajid and thank you for your report.

What version of Lago are you using?
We recently published a new version for lago-api (v0.5.2-alpha)

**Comment by vincent-pochet** [comment]
@stsajid to give us more context to find the source of the error, could you check in the logs of the API (with `docker-compose exec api tail log/production.log` command) for any `FATAL` error tag and sent it in here?

**NOTE:** Be careful before sending it as the logs might contain sensitive information from your system

**Comment by stsajid** [comment]
I am using the latest version as I started using Lago in a production environment a week ago.

I checked my api logs and getting the following errors when I view a created Customer.

<b> FATAL -- : [a20499e1-cd7e-40c4-9833-da247aa39516]   
[a20499e1-cd7e-40c4-9833-da247aa39516] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column invoices.customer_id does not exist
LINE 1: SELECT "invoices".* FROM "invoices" WHERE "invoices"."custom...
                                                  ^
): </b>

Getting the same error in logs when I create a new customer.

**Comment by vincent-pochet** [comment]
Hi @stsajid thank you very much for the error message.

It looks like some database migration were not performed correctly on your system.
We had some similar issues lately and we are working on enforcing our database migration process to prevent them.

Could you try the following command and try again to retrieve the customer list:
```bash
docker-compose exec api rails db:migrate
```

**Comment by stsajid** [comment]
Hi @vincent-pochet , Yeah some of the database migrations were not performed. I ran the command you mentioned and now the Customers module is working fine ! Thank you so much for helping out with this issue. Kudos !
