### ISSUE TITLE
[FEAT]: support aws-compatible s3 providers 

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago#90]
**Is your feature request related to a problem? Please describe.**
there are plenty of AWS-compatible S3 providers like https://github.com/minio/minio
they just need the base URL endpoint specifiying in the config along with the other existing s3 config variables...
not sure how much that will effect the existing implementation or how difficult it will be to change though.

**Comment by vincent-pochet** [comment]
Hello @c-nv-s thanks for bringing back this topic!

I've opened two Pull requests to address this request.
Hopefully it will be merged and released today as we are planing to release a new minor version

**Comment by vincent-pochet** [comment]
Hi @c-nv-s,

The support for `LAGO_AWS_S3_ENDPOINT` environment variable has been released in v0.5.3-alpha
