### ISSUE TITLE
Add free units and fixed units to the percentage pricing model

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#92]
## Problem description

The percentage pricing is always related to an amount (1% x 1000 USD, for instance). However, we might need to apply free units or a fixed charge to the number of transactions received. This information comes from the number of events ingested during a period.

**Comment by michaelponrajah** [comment]
## `Add free units and fixed units to the percentage pricing model` is now live in production 🎉

### Useful links
[Documentation](https://doc.getlago.com/changelog/free-units-percentage-model)
[Changelog](https://doc.getlago.com/changelog/free-units-percentage-model)
