### ISSUE TITLE
Pulumi deployment code

### ISSUE THREAD

**Issue by simenandre** [getlago/lago#93]
I love infrastructure as code, and we're trying out Lago for one of our customers. Therefore, we made some Pulumi code to deploy Lago to Kubernetes. Would that be something you'd like to be added somewhere? We can share it with you if you'd like.

We could even help contribute by creating a [multi-language Pulumi component](https://www.pulumi.com/blog/pulumiup-pulumi-packages-multi-language-components/) if this ends up being something you'd want to support.

I wanted to check in with you before publishing anything/opening a pull request, there is obviously some work needed before we can show it publicly. I didn't want to waste our time, if we are the only ones interested in it :)

**Comment by jdenquin** [comment]
Hello @cobraz !

We can definitely create a repository for this if that works for you!

**Comment by simenandre** [comment]
Sure thing! 👍

**Comment by jdenquin** [comment]
https://github.com/getlago/lago-pulumi here you are!
