### ISSUE TITLE
Apply subscription on a specific (past and future) date

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago#98]
## Problem

It's hardly doable to migrate existing customer with subscriptions in Lago as the product can't hold past subscription date than the one applied in the app.

**Comment by mtews** [comment]
Yes. This is absolutely 100% necessary if you want to get companies with existing subscriptions on board.

**Comment by jdenquin** [comment]
This has been released in the `v0.12.0-alpha` version.

**Comment by michaelponrajah** [comment]
## `Apply subscription on a past or future date ` is now live in production 🎉

Version `v0.12.0-alpha`
[Documentation](https://doc.getlago.com/docs/guide/plans/subscription#subscription-date)
[Changelog](https://doc.getlago.com/changelog/subscription-date)
